### ISSUE TITLE
MBP-RBP Parity (Phase 1)

### ISSUE THREAD

**Issue by tri-ltyyu** [RobotLocomotion/drake#10180]
## Description

This is to track the work required for the first phase of migrating RBP functionality to MBP. The success criteria for this is to have Anzu use MBP only. Other MBP requirements may be identified from use cases outside of Anzu. 

The issues 
- [ ] Full introspection of the mathematical representation of the physical model (to include WIP PR #10068)
- [x] Jacobians taken with respect to q (#9971 )
- [x] SignedDistanceToPoint support for sphere and box (#9779 ) 
- [x] Multi-body constraints for IK (#9341)

For reference only, #7025 has a list of RBP features requested by users. These may or may not be required for the goal of Phase 1.

**Comment by jwnimmer-tri** [comment]
> The success criteria for this is to have Anzu use MBP only.

Done (as of years ago).
