### ISSUE TITLE
python, multibody: Align modules with updated directories

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10207]
With @jwnimmer-tri's improvements to the directory structure, the Python API should match, with backwards compat shims and all that jazz.

Steps (in order):
- [x] #10254 Add new spellings as forwarding aliases (docs will be messy, but oh well)
- [x] Move attic items to **public** `pydrake.attic.` package.
  - [x] #10255 `solvers` (to flesh out pattern)
  - [x] #10505 RBT functionality in `multibody`
  - [x] Transitive related stuff
    - [x] #10506 `sensors`
    - [x] #10523 `controllers`
- [x] #10507 Split appropriate bindings in `multibody_tree_py.cc` into new spellings (but leave things like `MultibodyTree` behind)
- [x] #10534 Update newer Python code spellings in calling code (in Drake and Anzu)
- [x] #10594 Rename `multibody_tree_test.py`
  - Split into `plant_test` (for `plant` and `tree`) and `math_test`
- [x] #10593 Move attic-only example code to `pydrake.attic` (e.g. `rgbd_camera_example.py`)
- [x] #10595 Move attic-only unittests to `pydrake.attic`.
- [ ] Deprecate all forwarding shims (Goal: ~2019-02-06~ 2019-02-07)
  - [x] #10599 `attic/`
  - [ ] #10603 `pydrake.multibody_tree`

**Comment by jwnimmer-tri** [comment]
FYI In #9314, I proposed an approach for this where we first _add_ the new spellings, but not port much of anything to use them yet, and nor deprecate the old ones.  That lets us confirm that the old spellings still work, and keeps the PR more focused.  After that, we can perl pie everything in Anzu and Drake to the new spellings, and deprecate the old ones.  Something to consider.

**Comment by jwnimmer-tri** [comment]
FYI When fixing this issue, please also update `pydrake_pybind.h` documentation to use a different example for namespace vs package paths for module names.  The multibody_plant example there now is no longer true.

**Comment by EricCousineau-TRI** [comment]
Updated with plan of attack. The biggest PRs to review would be to split the `*_py.cc` stuff, and do the `pydrake.attic` moves.
