### ISSUE TITLE
Advanced (or requested) visualization features & discussions

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#10786]
This is an epic issue that tracks various "advanced" visualization requests. In this case, "advanced" means anything that is not a simple, literal visualization of the instantaneous state of the registered geometries. The preferred use of this issue is to create a *separate* issue with the detailed feature request (which will also serve as the platform for discussing the issue) and only link to it here with some form of summary that will allow other feature requesters to reasonably assess if their request has already been added. 

  - [x] #10780 Visualize multiple postures for the same MBP in the drake_visualizer 
    - Given a robot with corresponding registered illustration geometry, we want to be able to visualize multiple instances of that geometry in several poses simultaneously.
  - [x] #10809 Visualize data from the hydroelastic contact model.
  - [ ] Aggregate features for visualization.
  - [ ] Display body and joint (mobilizer) frames in both navigator and painter.
  - [ ] Translucent bodies and other objects.
  - [x] Display appropriately-sized center of mass for each body.
     - #17662
  - [ ] Display simulation notes, warnings, or errors (e.g., harvest a message log that can provide on-screen display of warnings such as a body's angular acceleration is unusually high for the physical situation at hand).

**Comment by RussTedrake** [comment]
Possibly related: #13038

**Comment by jwnimmer-tri** [comment]
It does not seem to me like this issue is actionable.  It's only purpose in life is as a table of contents for other issues?  It seems like there must be better ways to do that.  How about we close this one?
