### ISSUE TITLE
Migrate Homebrew formulae to homebrew-core where appropriate.

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#11052]
To save on the ever-increasing maintenance costs, avoid conflicts with `homebrew-core` packages, and benefit a potential wider audience for those formulae.

* [x] `embree` Homebrew/homebrew-core#37655
* [x] `kcov` Homebrew/homebrew-core#37659
* [x] `ospray` Homebrew/homebrew-core#38637

**Comment by EricCousineau-TRI** [comment]
Will save a significant amount of time.
(Every update requires a ~half day of fixing + rebuilding packages.)

**Comment by EricCousineau-TRI** [comment]
Most likely won't do `ipopt` due to `mumps` odd build system and non-transparent upstreaming process.
