### ISSUE TITLE
Update multibody call sites to use RigidTransform (part 3).

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#11193]
Overarching issue: https://github.com/RobotLocomotion/drake/issues/9865

Continuation of the work started in #10959 and #11064.

As with #11064, feel free to assign your name and address as many of these you'd like.

A brute force search of `Isometry3` within `drake/multibody` and `pydrake/multibody` revels the following 109 occurrences of `Isometry3` across 25 files (number counts how many times in that file):

- [x] ~bindings/pydrake/multibody/plant_py.cc: 5~ _(only used in deprecation warnings and compatibility shims)_
- [x] #11215 bindings/pydrake/multibody/test/inverse_kinematics_test.py: 1 @avalenzu 
- [x] #11393 bindings/pydrake/multibody/test/plant_test.py: 2 @jwnimmer-tri
- [x] ~bindings/pydrake/multibody/tree_py.cc: 3~ _(only used in deprecation warnings and compatibility shims)_
- [x] multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h: 1 @mitiguy 
- [x] multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc: 1 @mitiguy
- [x] #11215 multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.cc: 2 @avalenzu 
- [x] #11215 multibody/inverse_kinematics/test/inverse_kinematics_test_utilities.h: 2 @avalenzu 
- [x] #11215 multibody/inverse_kinematics/test/minimum_distance_constraint_test.cc: 2 @avalenzu 
- [x] #11394 multibody/multibody_doxygen.h: 2 @amcastro-tri
- [x] #11390 multibody/parsing/detail_urdf_geometry.cc: 5 @jwnimmer-tri
- [x] #11390 multibody/parsing/test/detail_scene_graph_test.cc: 5 @jwnimmer-tri
- [x] #11390 multibody/parsing/test/detail_sdf_parser_test.cc: 9 @jwnimmer-tri
- [x] #11390 multibody/parsing/test/detail_tinyxml_test.cc: 4 @jwnimmer-tri
- [x] #11390 multibody/parsing/test/detail_urdf_geometry_test.cc: 3 @jwnimmer-tri
- [ ] multibody/plant/multibody_plant.cc: 1: [here](https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant.cc#L448). @SeanCurtis-TRI, does it make sense to provide a `GeometryInstance` ctor taking a RT?
- [x] multibody/plant/multibody_plant.h: 25: they are **all deprecated APIs** within `#if DRAKE_DOXYGEN_CXX`.
- [x] multibody/plant/test/frame_kinematics_test.cc: 7 @mitiguy
- [x] multibody/plant/test/kuka_iiwa_model_tests.h: 1 @mitiguy
- [x] multibody/plant/test/multibody_plant_jacobians_test.cc: 1 @mitiguy
- [x] multibody/plant/test/multibody_plant_test.cc: 11 @mitiguy
- [x] multibody/test_utilities/spatial_kinematics.h: 5 @mitiguy
- [x] multibody/tree/fixed_offset_frame.h: 8 @mitiguy (already seems deprecated)
- [x] ~multibody/tree/multibody_tree.cc: 2~ _(captured in #10986 separately)_
- [x] multibody/tree/weld_joint.h: 2  @mitiguy

**Comment by amcastro-tri** [comment]
This has gone a big stale. I believe @mitiguy is working on some of this, could you confirm @mitiguy? I'll ask for more volunteers in the dynamics channel.

**Comment by mitiguy** [comment]
Yes @amcastro-tri  I am on this.  I got side-tracked slightly with numerical integrator test.

**Comment by mitiguy** [comment]
Monday update: Work to restart after onsite.

**Comment by mitiguy** [comment]
Progress update Monday May 20th -- background information only
All progress last week was on updating the Jacobian interface (Issue in progress #10155),
none on this issue.
Merged  PR#11414 12 days ago which checked off the following boxes in this issue:
multibody/benchmarks/kuka_iiwa_robot/drake_kuka_iiwa_robot.h: 1 @mitiguy
multibody/benchmarks/kuka_iiwa_robot/make_kuka_iiwa_model.cc: 1 @mitiguy
multibody/plant/test/frame_kinematics_test.cc: 7 @mitiguy
multibody/plant/test/kuka_iiwa_model_tests.h: 1 @mitiguy
multibody/plant/test/multibody_plant_jacobians_test.cc: 1 @mitiguy
multibody/plant/test/multibody_plant_test.cc: 11 @mitiguy

**Comment by amcastro-tri** [comment]
#11414 landed. Two `drake/multibody` bullets remaining, @mitiguy is it a good assumption that you'll address them.

@SeanCurtis-TRI, regarding the last bullet mentioning an additional `GeometryInstance` ctor, is that a sensible solution?

**Comment by mitiguy** [comment]
Yes - I'll address them this week.

**Comment by amcastro-tri** [comment]
Excellent! we are only one bullet away from resolving this one!
Thanks to everyone who contributed.

**Comment by jwnimmer-tri** [comment]
FWIW I don't think we should do anything about the last checkbox -- I think we should close this now.

SceneGraph is all-in on Isometry3; we shouldn't try to start shaving that yak under the umbrella of this issue.

**Comment by mitiguy** [comment]
Closed this issue and opened issue #11549 which deals specifically with SceneGraph.
