### ISSUE TITLE
py mbp: Expose autodiff and symbolic scalar types

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11240]
Relevant Slack discussion:
https://drakedevelopers.slack.com/archives/C2CK4CWE7/p1555082817001300?thread_ts=1555024805.009600&cid=C2CK4CWE7

> Thanks Russ and Michael!
> Russ: do you mean something like this?
> ```plant_sym = plant.ToSymbolic()
> q = prog.NewContinuousVariables(plant.num_positions())
> context = plant_sym.CreateDefaultContext()
> plant_sym.SetPositions(context, q)```
> If yes, here I get: `'System_[Expression]' object has no attribute 'SetPositions'`.

Check list:
- [x] #11384 Remove the, uh, bad legacy dependencies that I left; currently we have: (`-->` representing depends-on)
  * `.autodiff, .symbolic --> .math --> .common.eigen_geometry`, but really we want
  * `.math --> .common.eigen_geometry --> .autodiff, .symbolic`
- [x] #11383 Start cleaning up `value` stuff
- [x] #11386 Consolidate testing utilities for NumPy matrix comparisons, esp. for extra dtypes
  - Overarching issue now tracked by #11385, but just need PR to smooth out this work
- [x] #11382 Expose dtypes for `.common.eigen_geometry`
- [x] #11563 Expose dtypes for `.common.math`
  - [x] `RotationMatrix` first
  - [x] `RigidTransform`, `RollPitchYaw`
- [x] #11590 Expose dtypes for `.multibody.math`
- [x] #11614 Expose dtypes for `geometry`
- [x] #11633 Expose dtypes for `.multibody.tree`
- [x] #11633 Expose dtypes for `.multibody.plant`

\cc @TobiaMarcucci @RussTedrake @hongkai-dai

**Comment by EricCousineau-TRI** [comment]
Added checklist. I'm going to tackle the first few items to figure out the general procedure and do some much-needed cleanup.
After binding `.common.eigen_geometry`, may request help from @m-chaturvedi.

\cc @jamiesnape 

WIP Branch: https://github.com/RobotLocomotion/drake/compare/master...EricCousineau-TRI:issue/11240-wip

**Comment by EricCousineau-TRI** [comment]
Per Slack convo, other suggestions for looking at scalar-type binding:
https://github.com/RobotLocomotion/drake/blob/2df723d/bindings/pydrake/systems/primitives_py.cc
https://github.com/RobotLocomotion/drake/blob/2df723d/bindings/pydrake/systems/framework_py_values.cc

This is a bit more advanced, so take it with a grain of salt:
https://github.com/RobotLocomotion/drake/blob/2df723d/bindings/pydrake/systems/framework_py_systems.cc

**Comment by EricCousineau-TRI** [comment]
Primary diff with scalar type change for eigen geometry: https://github.com/RobotLocomotion/drake/commit/fc331ee68ad658c6ee26f394bef7326886e371f8

https://drake.mit.edu/python_bindings.html#differences-with-c-api

**Comment by mpetersen94** [comment]
Is there an eta for autodiff support of RigidTransform/RotationMatrix in python?  I'm happy to help with the process if that would accelerate the timeline at all.

**Comment by m-chaturvedi** [comment]
I'm working on it.  I need to write the relevant tests for it.  I need to know from Eric which all methods need to be exposed other than `RigidTransform` and `RotationMatrix`.

**Comment by EricCousineau-TRI** [comment]
Er, added my thumbs-up without answering!
To clarify, it would be best to bind all methods that are scalar-type depended, unless there are issues.
If there gets to be too much boiler-plate for instantiating unittest test cases, then it should be simple enough to simplify that, helping with aliases and all that.

**Comment by EricCousineau-TRI** [comment]
@mpetersen94 -- @m-chaturvedi just landed that PR. At present, the only thing not fully supported is `RigidTransform_[T].translation()` - but that should be resolved via #11575.

**Comment by gizatt** [comment]
As I understand it this is blocking Python binding of `StaticEquilibriumConstraint` -- for timeline purposes, I'd love to have access to those bindings in a week or so, but I can adjust if that looks like it won't happen. Thanks!

**Comment by EricCousineau-TRI** [comment]
Per f2f, we will target next Friday, June 14th. Thanks!

**Comment by EricCousineau-TRI** [comment]
Per Slack convos, @m-chaturvedi is almost there; wrangling some issues with scalar type conversion with MBP+SG and matrix aliasing per #8116

**Comment by EricCousineau-TRI** [comment]
Done! Thanks @m-chaturvedi!

**Comment by EricCousineau-TRI** [comment]
(Even though #11575 is not yet resolved, can still fix that separately without needing this to be open.)
