### ISSUE TITLE
models: Should migrate data to `RobotLocomotion/models` per doc advice

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11913]
Follow-up to #10811.

To relocate:
- [x] `examples/atlas/urdf/meshes`
- [ ] `examples/pr2/models/pr2_description/meshes`
- [x] `manipulation/models/allegro_hand_description/meshes`
- [x] `manipulation/models/iiwa_description/iiwa7`
- [x] `manipulation/models/iiwa_description/meshes`

To deprecate and remove:
- [x] `examples/irb140/urdf/meshes` (#13831)
- [x] `examples/kuka_iiwa_arm/models/objects/meshes` (#13831)
- [x] `manipulation/models/wsg_50_description/meshes` (#13693)

**Comment by EricCousineau-TRI** [comment]
FYI @IanTheEngineer

**Comment by jwnimmer-tri** [comment]
This is confusing a few people every month, so I'm going to work on it.

**Comment by jwnimmer-tri** [comment]
\CC @IanTheEngineer

**Comment by jwnimmer-tri** [comment]
It's possible that the resolution of #13942 will end up being a prerequisite for this work.  If we decide that the sdformat / urdf files should move as well, it probably makes sense to do them as part of the same file relocation as the meshes.

**Comment by jwnimmer-tri** [comment]
The only remaining one to port is the PR2. It's complicated by the fact that we're currently reprocessing those models with `stl2obj` and then installing the reprocessed copies. The easy fix is to commit the reprocessed files into the models repository. It might be worth seeing if there is any a more elegant solution available instead.

**Comment by jwnimmer-tri** [comment]
I'll roll the one remaining task into #13942, so we can close this one.
