### ISSUE TITLE
Update ForceElement APIs

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#13350]
This work started in #13258.

Currently `ForceElement` APIs have a number of problems:
1. virtual `CalcFoo()` methods explicitly take cache entries. They should only take a context.
2. Scalar conversion should stop taking a MultibodyTree (now an `internal::`). This at the same time will disable the use of `MBT::get_variant()` which has the side effect of forcing authors to save indexes instead of pointers/references (not guaranteed to exist when scalar converting)
3. Energy methods are required. They should be made optional for quick prototyping, requiring only the force computation.
4. Documentation on how to write custom force elements should be enhanced to facilitate this.

In #13258 we did a first pass to (1)-(4). This first pass was performed in order to enable backwards compatibility and avoid breaking the older API, enabling the work in this Epic to be performed in several passes. Remaining work entails:

- [ ] Update existing Drake force elements to use updated API in #13258
- [ ] Deprecate methods withing the Doxygen `@cond` documenting with a TODO the older APIs using `internal::` cache entries and `internall::MultibodyTree`.
- [ ] Enforce the implementation of `DoAddForceContribution()` by making it pure virtual.
- [ ] Finally, remove (after the 3 months grace period) the deprecated APIs.

**Comment by jwnimmer-tri** [comment]
Closing as duplicate of #12697.
