### ISSUE TITLE
Re-org and rewrite of distribution, installation, and build docs

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#13539]
There are numerous known issue and usability hurdles with Drake's documentation for how users consume Drake releases, nightlies, source builds, pydrake, etc.

It will be most efficient to take a big swing at all of these at once in a single editing pass, because some of the problems relate to how the information is organized, rather than the specific facts being presented.

I will link all of the relevant issues here:
- [x] #9277 Docs for using Drake linters from downstream Bazel projects
- [x] #10550 /opt is read-only on mac
- [ ] #10605 Document deprecation policy and tools
- [x] #10624 Add instructions for debugging python bindings from CMake install 
- [x] #12175 Need to improve docs for CMake build options (e.g. SNOPT)
- [x] #12306 Not clear how to install drake in installation-from-source instructions
- [x] #13066 How to use bazelrc
- [x] #13187 Should add tips on debugging PYTHONPATH issues 
- [x] #13202 Clarify minimum macOS version for pydrake 
- [x] #13210 Note requirement of X server for rendering 
- [x] #13500 python_bindings.rst should have installation instructions moved to installation doc pages 
- [x] #13603 document the fact that gurobi and mosek are not available in the binary builds
- [x] #13639 Crash in drake visualizer
- [ ] RobotLocomotion/drake-external-examples#108 drake_bazel_external vs commercial solvers
- [x] #9500 [citation] _Provide preliminary ROS1 support w/ catkin, document recommended workflow_
- [ ] #13514 [citation] _ARM64 support_
- [x] #13391 [citation] _Dropping Ubuntu 18.04 (Bionic) support_
- [x] [#14685](https://github.com/RobotLocomotion/drake/issues/14695#issuecomment-786689621) In from_binary.html, the "binary packages" links to an unhelpful github comment.

Items marked as _[citation]_ should be cited from the new documentation to encourage further discussion or provide context, but the issue will not be resolved by documentation changes.

**Comment by jwnimmer-tri** [comment]
We'll kick this off on week of Monday 7/13.

**Comment by jamiesnape** [comment]
I would add the following (feel free to merge up top):

- [ ] #14029 drake-lcm-spy gives NoClassDefFoundError in Docker
- [ ] #13924 cart-pole example throws exception in cmake project

**Comment by jwnimmer-tri** [comment]
This is essentially done now.  I've filed #22530 to kick off a last look, but most/all of the acute problems noted above have been resolved, at least in part.
