### ISSUE TITLE
[render] RenderEngineGl has incomplete implementation of RenderEngine interface

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#13617]
We've ported `RenderEngineGl` from Anzu back to Drake (#13584). However, the ported code is incomplete:

- [x] The ability to display the rendering is missing. (resolved by #13626)
- [x] Unable to render label images. (resolved by #13659)
- [x] Unable to render color images. (resolved by #14226 and #14260)
- [x] Needs to support full intrinsic specification (see, #11880 for details)
- [ ] Add RenderEngineGl to `render_benchmark.cc` (#14540)

This epic PR tracks the work for the `RenderEngineGl` to be "complete" (in the sense that it has the same functionality as the other `RenderEngine` implementations).

**Comment by jamiesnape** [comment]
When I read the title, I thought that it mean RenderEngineGl required missing features of a certain OpenGL version. Do you mean "RenderEngineGl is missing (required) features"?

**Comment by SeanCurtis-TRI** [comment]
@jamiesnape Yep. You're dead on. I've tweaked the title so it isn't so confusing.

**Comment by SeanCurtis-TRI** [comment]
Opening this back up to make sure we add `RenderEngineGl` to the render benchmarks.
