### ISSUE TITLE
Upgrade Drake SDFormat 1.8 (for Model Composition)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#14295]
Proposal: [SDFormat: Model Composition](http://sdformat.org/tutorials?tut=composition_proposal)
Towards: https://github.com/osrf/sdformat/issues/278

Assigned to me, but will reassign to @azeey once permissions are setup

Suggested PR train:

- [x] #14705 Upgrade to `libsdformat10`
- [x] #14848 Upgrade to `libsdformat11` w/ minimal changes
- [x] ~#14401~ Upgrade to use SDFormat 1.8, without interface API
  - [x] #15099 Must avoid registering implicit model frame in Drake
- [ ] #15140 Upgrade to use SDFormat 1.8, **with** interface API

**Comment by EricCousineau-TRI** [comment]
Example PRs to examine:
- #13128
- WIP for phantom: https://github.com/RobotLocomotion/drake/pull/13758
- WIP for developing: https://github.com/RobotLocomotion/drake/pull/12061
- https://github.com/RobotLocomotion/drake/pull/12505

Files:
- https://github.com/RobotLocomotion/drake/blob/0c5affa7f913d104d8f10559f0fd012fd8bf8797/multibody/parsing/detail_sdf_parser.cc + unittest + header
- https://github.com/RobotLocomotion/drake/blob/0c5affa7f913d104d8f10559f0fd012fd8bf8797/multibody/parsing/detail_scene_graph.cc + unittest + header
