### ISSUE TITLE
[geometry - dev] Support Bvh support for deformable simulation

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#15080]
## The problem

Current code for computing contact between a [deformable volume mesh and rigid surface mesh](https://github.com/RobotLocomotion/drake/blob/master/multibody/fixed_fem/dev/deformable_contact.cc#L57-L60) iterates through all tet-tri elements. This O(MN) algorithm is *highly* inefficient.

For the same reason hydroelastic contact makes use of bounding volume hierarhcies (Bvh) to accelerate the query by culling pairs of elements that are obviously not colliding, the deformable contact would likewise benefit. However, we can't make direct use of the existing Bvh infrastructure because, it is designed assuming that the meshes are immutable (the exact opposite of a deformable mesh). So, we need a solution that will allow for a mesh whose vertex positions change (but with unchanging topology), and a Bvh that accommodates those changes.

Our current Bvh infrastructure uses an oriented-box bounding volume. This is appropriate for static meshes (as the cost for constructing a good Obb Bvh is high). Deformable meshes need to be refit over and over again. It's more typical to use an axis-aligned bounding box (Aabb). It provides a better balance of update cost with culling benefit. However, we still want to have the benefit of colliding a Aabb-Bvh for deformable meshes against the Obb-Bvh for the static, rigid meshes.

While it is possible to generate a bunch of code and dump it into `fixed_fem/dev`, we're not going to do that for the following reasons:

  1. It leads to a *mountain* of duplicated code with the current Bvh code.
  2. Even attempting to do that will still require modifications *outside* of `fixed_fem/dev` to support Bvh acceleration of the query.
  3. It is the expectation that `geometry` will eventually own all of the entities necessary to support contact queries with deformable geometry. This is merely the logical extension of the current code in that direction.

So, rather than fragment the code across "master" and "dev", we're going to put the majority of the code in `geometry/` proper, and leave a smaller imprint in `dev`.

## The Plan

- [x] #15058 - introduce Aabb into the `geometry/proximity` ecosystem.
- [x] #15084 - Reframe the Bvh to be bounding volume type agnostic. We can build one with Obb or Aabb and can collide the two against each other.
- [x] #15117 - Add `MeshDeformer` for providing interface for moving mesh vertex positions and combine it with all previous components to create a `DeformableVolumeMesh`.
- [x] #15221 - Add updater for refitting a Bvh to the underlying mesh.
- [x] #15287

**Comment by DamrongGuoy** [comment]
It looks good.  Thanks for providing the plan.
