### ISSUE TITLE
c++ design for Drake::Function

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#1533]
Recommendations:
- [ ] flat metaprogramming concept for functions (vector to vector)
- [ ] should be able to implement sparsity pattern explicitly
- [ ] also provide method to automatically extract sparsity pattern (by implementing a scalar type that gets turned on whenever it's touched, and throws an error if it, e.g. gets converted to a boolean because it's being used an if statement -- by overloading operator bool(), plus comparison operators, etc).  have to tell the user that it could make errors (e.g. branching on a system property that changes after computing the sparsity pattern).

**Comment by RussTedrake** [comment]
A few kore thoughts:

We've already decided on the complexity hierarchy for functions (polynomial, linear, etc).  Also need to declare the sparsity.

The system functions are simply multiple-argument functions.  The output has a linear, etc relationship to each of the inputs.  And a sparsity pattern.  All of the releavant system properties (time-invariance, direct feedthrough, control affine, etc) can be derived if we know this structure for the system functions.  That is the best way to declare them.

even the manipulator form should be a special case.
