### ISSUE TITLE
Roadmap for Hydroelastic Contact debut

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#15796]
## Summary

Hydroelastic contact has been in development limbo for a number of years. It has intentionally been developed in a quasi sub rosa manner to allow developer freedom as we evaluated how best to implement it and integrate it with Drake. Its core functionality has been in place long enough and we've had enough chances to kick its tires and exercise its APIs that we can see the end of the tunnel. We're *just about* ready to promote it to a full member of the Drake feature set.

There are still a number of items that we want to achieve before we pull the trigger, as promotion to "full feature" entails all of the cost of API changes (i.e., deprecation) for any future changes. Below we've listed various tasks related to the continuing development of hydroelastic contact. They've been coarsely categorized into prerequisites for the debut, and those that can follow after. Each of the prerequisite tasks has a point of contact assigned to it -- this is the developer responsible for making sure it's done in time for the promotion.

### Prerequisites for promotion to full feature
  - [x] Technical debt clean up
      - [x] #15903
          - These are thin, impoverished wrappers of Vector3<T>. We'll simply expose the functional type.
      - [x] Eliminate `Volume*Index` and `Surface*Index`. (@SeanCurtis-TRI )
          - The index types introduce a fair amount of verbosity without much value. The public API doesn't have functions that take multiple index types, therefore the primary benefit is missing. On the other hand, constructing meshes is a penance.
          - The strategy here will be five PRs. Four individual PRs will tackle each of the four index types. They will
              -  change the strongly-typed index into an alias for `int`.
              - Remove all drake-internal references to the old type name.
           - The fifth PR will do the final clean up, coordinating the removal of the type names and presage an Anzu PR.
           - The implementation of the strategy can be found here:
              - [x] #15913
              - [x] #15912
              - [x] #15932
              - [x] #15933
              - [x] #15942
      - [x] Clean up documentation and public API to remove references to "soft" geometry. (@DamrongGuoy)
          - It has been decided that the term "soft' will remain exclusively in the domain of truly deformable geometry. In the hydroelastic domain we'll use the term "compliant" to contrast with "rigid".
          - #16218 
          - #16224 (And update anzu.)        
      - [x] Address the "elastic_modulus" material lie. (@DamrongGuoy)
          - Hydroelastic contact makes use of a property called "elastic modulus". While that would typically be a material property, the way hydroelastic property uses it, it *isn't* actually a material property. This will inevitably lead to surprise and confusion. We've brainstormed some initial options to alleviate this. Further discussion is required:
              - Simply rename it to something proprietary (e.g., "hydroelastic modulus") and document its idiosyncracies.
                 - #15911
                 - #15924 
                 - #15928
              - Change to a *different* value that has a stronger "material"-like property. Currently, the use of "elastic modulus" is essentially "maximum pressure" (i.e., the most pressure that a geometry can exert at contact at its deepest penetration). If, instead, we were to change it to "pressure per unit penetration distance", then it would be decoupled from the scale of the geometry. (Note: there's some subtle nuance here when working with volume meshes with anisotropic measures and a single layer of tets.) (Special note: making this work for anisotropic shapes require "rigid cores" that can support different maximum pressure based on the direction the contact comes from. A single *shared* vertex in the center means every tet has the same maximum pressure, regardless of its dimension.)
      - [x] A user can set "hydroelastic_modulus" on a "rigid" geometry and that act affects the dynamics. (@joemasterjohn)
          - "hydroelastic_modulus" should always strictly be infinity on rigid objects.
          - Resolution: Force `HydroelasticEngine` to ignore `hydroelastic_modulus` on any geometry declared "rigid" and add a warning to the parser when a user adds a `drake:hydroelastic_modulus` tag to a rigid geometry. (Advanced) users could still accidentally add the property manually using the `SceneGraph` API, but the value will be ignored at the lowest level in `HydroelasticEngine` regardless.
          - #16322
      - [x] `hydroelastic_modulus` should not be set by the [`AddContactMaterial`](https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity_properties.h#L120) method. (@rpoyner-tri )
          - It should be moved into each of the `AddSoftHydro...Properties()` methods in the same file.
          - `AddContactMaterial` should only include those most *generic* of properties. `elastic_modulus` was added originally based on the mistaken understanding that it also contributed to point contact. It does not. It is strictly a hydroelastic property and should be set at the same time that other hydroelastic properties are configured.
          - #16009
          - #16046 (@DamrongGuoy)
      - [x] `SurfaceMesh` becomes ambiguous in the presence of `PolygonSurfaceMesh`. Rename it to `TriangleSurfaceMesh` (and change all related entities/methods). (@SeanCurtis-TRI )
        - [x] #15962
        - [x] #15993 (@DamrongGuoy)

  - [x] Features
      - [x] Compliant-compliant contact (declared necessary after discussions about PR campaign) #16040 
      - [x] User guide (@joemasterjohn) #16449 
          - A doxygen-rendered guide which describes (at an intuitive level) hydroelastic contact, with appropriate references to published papers and code. Its emphasis is to be a one stop guide for users to know how to enable hydroleastic contact, the vagaries of working with it, how to define appropriate properties, and various tips and tricks culled from the tribal knowledge. ~~For those who have access to TRI's drive, the [draft is here](https://docs.google.com/document/d/1eSHIyFdRzgnoli4REihIMiCBLFc9LKzLpmnPkv6m42A/edit#).~~
          - ~~Make sure the User Guide suggests how to deal with graph-coloring problems, i.e., ideally we want multiple compliant geometries in contact, but right now we have to live with rigid-compliant contacts. (Compliant-compliant contact will be available end of CY22Q1 or later.)~~
      - [x] Blog post (@sherm1)
          - This isn't a "prerequisite" so much as it is coincident. Some of the text will probably be borrowed from the user guide.
      - [x] Full support for a "polygonal" contact patch. (@SeanCurtis-TRI )
          - The polygonal contact patch is a representation of the contact surface with fewer total elements.
          - We will also have full visualization support in `drake_visualizer` (but not `Meshcat`, see below).
          - The plan for introducing the feature into master consists of many PRs in rounds. Each round consists of changes that can be considered independently. Each round has one or more dependencies in previous rounds. The plan is subject to change as the details are fleshed out.
              - [x] Round 1
                  - [x] #16102
                  - [x] #16111
                  - [x] #16112
              - [x] Round 2            
                  - [x] #16115
                  - [x] #16122
                  - [x] #16120
              - [x] Round 3
                  - [x] #16126
                  - [x] #16134
                  - [x] #16160
              - [x] Round 4
                  - [x] #16163
                  - [x] #16162
                  - [x] #16164
              - [x] Round 5
                  - [x] #16177
              - [x] Round 6
                  - [x] #16176
              - [x] Round 7
                  - [x] #16175
      - [x] Confirm policy for coordinating contact surface type (sparse polygon or dense triangle) with `MultibodyPlant` discrete/continuous mode. (@DamrongGuoy)
          - The polygonal mode is currently the *natural* partner of `MulitbodyPlant`'s efficient discrete mode. But in master (as of 9/20/2021), the user must explicitly opt in. Potentially, we would want to change that default. Or not. Either way, it needs to be explicitly considered.
          - (October 25, 2021, edit by @DamrongGuoy) We had an internal TRI meeting and the conclusion was:
              - By default, for continuous-time systems, we will use triangles, and for discrete-time systems, we will use polygons
              - @SeanCurtis-TRI will create a new API that fixes continuous-time systems with triangles and fixes discrete-time systems with polygons.
              - The older experimental API (MbP::set_low_resolution_contact_surface(bool use_low_resolution)) will be removed. 
              - [x] @rpoyner-tri will extend the new API to let users choose between triangles and polygons and update [MultibodyPlantConfig](https://github.com/RobotLocomotion/drake/blob/master/multibody/plant/multibody_plant_config.h) as needed.
                - #16238
      - [x] All relevant public APIs fully bound in python (i.e., normal exercise of hydroelastic contact should be equally available in python). (@jwnimmer-tri  )
          - Note: resolving this resolves the issue as documented in #15643
          - #16212

### Post-promotion development
These items are nice to have but not needed before releasing hydroelastic contact model officially.
  - [ ] ~~Examples of how to deal with ideally compliant-compliant contact, but we work around it using rigid-compliant contact.~~
  - [ ] Performance tuning. (@DamrongGuoy)
      - Check realistic examples to identify hotspots after refactoring.
         - It might include evaluating contact pressure via barycentric coordinates or Cartesian coordinates.
         - It might include cleaning up HydroelasticTractionCalculator<T>::   ComputeSpatialForcesAtCentroidFromHydroelasticModel() for triangles and polygons.
         - #16197 
  - [x] Tutorial (in python notebook)
      - Allow users to play with hydroelastic properties interactively and immediately see the effect. A powerful complement to the user guide.
      - #19467
  - [x] Visualization of hydroelastic contact results in Meshcat (C++ version, *not* python)
    - #16913
    - #17599
    - #17681
  - [x] Support compliant geometries from arbitrary meshes (instead of just from platonic primitives).
     - There are two different complementary avenues to support this
         - Define an off-line workflow that users can use to take an OBJ and create a volume mesh and pressure field on disk and have Drake parse those files.
         - #17837
         - Implement, in Drake, that pipeline on-line.
  - [x] Extend examples to include a case where hydroelastic properties are fully defined in URDF/SDF files.
    - #15804 
    - #16668 
    - #16534 
    - #17959 
    -  #20034
  - [x] Allow configuring `MultibodyPlant` to use a lower order of integration  (and the polygonal contact surface) even in continuous mode.
         - #16238 
         - #16257 
         - #16258 
         - #16244 
  - [x] Currently we require explicit declaration of all relevant parameters (e.g., elastic modulus). We should explore if any of these values can be defaulted to ease the burden of engaging/declaring hydroelastic contact.
    - #19709

**Comment by rpoyner-tri** [comment]
There's a lot of soft/compliant term use to review:

```
$ git grep -i '\bsoft\b' |grep -v /dev/ |wc -l
299
```

**Comment by DamrongGuoy** [comment]
I confirm that for `Technical debt clean up`, we are quite good now, right? All the data structures (*Vertex, *Index, *Mesh, *Field\*) are quite stable now. It's safe to expect no major merge conflict in my draft PR #15545 (compliant-compliant contact) anymore, right?  I'll focus this month on compliant-compliant contact.

**Comment by SeanCurtis-TRI** [comment]
@DamrongGuoy I don't know how entangled the compliant-compliant contact is with the compliant-rigid mesh contact, but that code is getting heavily touched due to incorporating the `PolygonSurfaceMesh`. Given the size of that effort, I would prefer not to have to rebase it to accommodate compliant-compliant. Keep that in mind.

**Comment by DamrongGuoy** [comment]
@joemasterjohn will take care of this roadmap now, so I can focus on compliant-compliant contact #16040.

I remove myself from the list of assignees.

**Comment by rpoyner-tri** [comment]
There is not much value left in keeping this open. I will peel off the remaining items of interest to separate issues, and close this one.

**Comment by jwnimmer-tri** [comment]
@rpoyner-tri is the peeling complete?  Can we close this now?

**Comment by rpoyner-tri** [comment]
I've gone through the original checklist. I'm pretty satisfied we have at least MVP support for everything. The only open item is post-release performance tuning; I feel like important pain points will make themselves obvious over time.

Closing.
