### ISSUE TITLE
Remove yaml-cpp as public dependency

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#15868]
In #7451 and #15815 we discuss the public header file dependencies of Drake.  In general, it's to our advantage to keep our public header footprint small, to maximize compatibility with our users who might want to use different version of those dependencies (e.g., #1183 or #14967).  For most libraries we depend on, we should build them with private symbols that only we can see, so that downstream users can build their own, different version if they need to.

For vocabulary types like Eigen, it's appropriate to have a public dependency.  However, for yaml-cpp, we mostly only use it for parsing, not as an abstract syntax tree (AST), so there is no great reason why it's currently a public dependency.  Furthermore, it is a C++ library and does not try to handle ABI compatibility carefully, so has a somewhat higher chance of causing trouble than other, simpler libraries.  (It's upstream maintainer is also no longer very active, and is seeking volunteers to take over.)

We should implement a minimal AST on our own that we can code against (in both our h and cc files), and only rely on yaml-cpp for it's parsing front-end, private to our cc files.

This will also enable us to easily pull in newer revisions of yaml-cpp with parser fixes.  As it stands now, because it's a public dependency, we are stuck being pinned to the Ubuntu version.

Relatedly, it's AST uses a confusing form of value syntax that actually has mutable reference semantics, so the readability of our code that's written against that API is a constant struggle.  Using our own AST will be an improvement on that front as well.

- [x] #15865
  - [x] #15910
  - [x] #15934
    - [x] #15940
  - [x] #15894 
- [x] #15866
- [x] #15867
  - [x] #15890
- [x] #16000
- [x] #15902
- [x] Port all of Drake to the new sugar
  - [x] #15998
  - [x] #16049
  - [x] #16050
- [x] Port all of Anzu to the new sugar
  - [x] #16059
  - [ ] Add option to specify ignored keys.
- [x] #16083
- [x] #16057
- [x] The "Archive" classes are all marked "Advanced".  Should they just be internal, instead? => deferred to #16706.
- [x] After the deprecations die on 2022-03-01, make the dependency actually private:
   - [x] #16701 Remove yaml-cpp from `drake-config.cmake` and the related installation infrastructure.
   - [x] #16701 Switch yaml-cpp to build from source with hidden symbols and upgrade to the latest tagged source release, and remove our one vendored upstream file from Drake.
