### ISSUE TITLE
[hydro] Minor clean up for hydro roadmap.

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#15993]
The effort to prep hydroelastic contact for Jan 2022 release has had some hiccups. Changes that missed some small extraneous details. This issue attempts to capture them so that they can be cleaned up.

- [X] Bvh and related tests #15995
    - [X] `bvh.h` has [redundant documentation about index types being comparable](https://github.com/robotlocomotion/drake/blob/0e81c4dcf1effea385140a13c6d71219f7a61c5e/geometry/proximity/bvh.h#L114-L116). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810). The sentence should simply be cut.
    - [X] `bvh_updater_test.cc` uses [verbose language for instantiated faces](https://github.com/robotlocomotion/drake/blob/0e81c4dcf1effea385140a13c6d71219f7a61c5e/geometry/proximity/test/bvh_updater_test.cc#L73). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810). 
    - [X] `obb_test.cc` uses [verbose language for instantiated faces](https://github.com/robotlocomotion/drake/blob/0e81c4dcf1effea385140a13c6d71219f7a61c5e/geometry/proximity/test/obb_test.cc#L346). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810). 
    - [X] `bvh_test.cc` uses an [overly verbose/indirect method for instantiating mesh faces](https://github.com/robotlocomotion/drake/blob/540fb82aa9b67ded8ea531349609e2bdc9b27dde/geometry/proximity/test/bvh_test.cc#L398). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810). 
        - Fixed as part of #15962.   
- [X] `mesh_half_space_intersection.h` has some [bad language in documentation](https://github.com/robotlocomotion/drake/blob/0e81c4dcf1effea385140a13c6d71219f7a61c5e/geometry/proximity/mesh_half_space_intersection.h#L146). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810). 
    - Fixed as part of #15962.   
- [X] `mesh_intersection_test.cc` uses [verbose language for instantiated faces](https://github.com/robotlocomotion/drake/blob/0e81c4dcf1effea385140a13c6d71219f7a61c5e/geometry/proximity/test/mesh_intersection_test.cc#L1083). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810).
    - #15996
- [X] `hydroelastic_traction_calculator.h` has [confusing language in its documentation](https://github.com/robotlocomotion/drake/blob/0e81c4dcf1effea385140a13c6d71219f7a61c5e/multibody/plant/hydroelastic_traction_calculator.h#L29-L30). Noted in [this review](https://github.com/RobotLocomotion/drake/pull/15962#pullrequestreview-788745810). 
    - #15997 

Relates #15796
