### ISSUE TITLE
Port examples away from drake-visualizer

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#16216]
We should stop using `drake-vizualizer` in our examples (see #16215).  This issue maintains the checklist of programs that we'll need to port to use meshcat (or otherwise).

Add your username after any items you'd like to take on.

Examples:
- [x] examples/acrobot (#16263)
- [x] examples/allegro_hand (#16452)
- [x] examples/atlas (#16452)
- [x] examples/compass_gait (#16452)
- [x] examples/kinova_jaco_arm (#16452)
- [x] examples/kuka_iiwa_arm (#16452)
- [ ] examples/manipulation_station
- [x] examples/mass_spring_cloth (#16248)
- [x] examples/multibody/acrobot (#16452)
- [x] examples/multibody/cart_pole (#16452)
- [x] examples/multibody/cylinder_with_multicontact (#16452)
- [x] examples/multibody/four_bar (#16452)
- [ ] examples/multibody/inclined_plane_with_body
- [ ] examples/multibody/pendulum
- [ ] examples/multibody/rolling_sphere
- [x] examples/multibody/strandbeest (#16436)
- [x] examples/particles (#16452)
- [ ] examples/pendulum
- [x] examples/planar_gripper (#16452)
- [ ] examples/quadrotor
- [x] examples/rimless_wheel (#16452)
- [ ] examples/rod2d
- [ ] examples/scene_graph
- [x] examples/simple_gripper (#16452)

Tests:
- [ ] geometry/profiling/contact_surface_rigid_bowl_soft_ball
- [ ] manipulation/models/realsense2_description/test/realsense_parse_test (@jwnimmer-tri)
- [x] manipulation/models/ycb/test/parse_test (#16220)
- [ ] multibody/contact_solvers/test/multibody_sim_driver
- [ ] multibody/optimization/test/optimization_with_contact_utilities
- [ ] multibody/plant/test/multibody_plant_hydroelastic_test
- [ ] multibody/plant/test/multibody_plant_reaction_forces_test

**Comment by SeanCurtis-TRI** [comment]
Worth noting that *anything* using `ContactResultsToLcm` to visualize hydroleastic contact has no `drake_visualizer`-free substitute. Adding this missing functionality is one of the prereqs.

**Comment by xuchenhan-tri** [comment]
I'll take on one (the example I introduced) as an experiment. I may take on more in the future as I get more working knowledge of MeshCat.

**Comment by jwnimmer-tri** [comment]
#16248 actually raises an interesting policy question that I failed to consider during review.  We _could_ have both visualizer options enabled for demos like these, even if we document / steer people towards meshcat as the preferred one.  In this example at least, it's only an extra line of code for each one.

**Comment by xuchenhan-tri** [comment]
What's the point of keeping the drake_visualizer option if we are not going to deprecate it in the coming months?

**Comment by jwnimmer-tri** [comment]
The current plan in #16215 says that for Ubuntu 20 (only), we'd continue to support `drake-visualizer` through early 2024.  For that, we should probably preserve at least _some_ examples that allow for demonstrating and regression testing it.  I suppose doing it for all of them would be pointless (or even misleading), though.

Maybe we nominate the `examples/kuka_iiwa_arm` as the one that should preserve `drake-visualizer` support, and everything else swaps to be meshcat-only.

**Comment by jwnimmer-tri** [comment]
This will be mostly finished as of #19781.  Instead of spending time porting all of the demos to Meshcat, we'll just switch them to use Meldis and call it a day.

There are a few hydroelastic demos that still seem to require `drake_visualizer`.  Those will be tracked in #19870.
