### ISSUE TITLE
[geometry] Incomplete/inconsistent bindings for hydroelastic APIs

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#17625]
### What happened?

A survey of the hydroelastic API bindings have revealed a number of issues.

#### Pressure fields and their accessors on `ContactSurface`
- [X] `ContactSurface::tri_e_MN()` (resolved by #17637)
- [X] `ContactSurface::poly_e_MN()` (resolved by #17637)
- [x] `TriangleSurfaceMeshFieldLinear` (the whole class)
  - [X] Partially resolved by #17637. It cannot be constructed, but the field returned by `ContactSurface` can be evaluated.
  - [x] Determine policy for constructing in python. #17799
- [x] `PolygonSurfaceMeshFieldLinear` (the whole class)
  - [X] Partially resolved by #17637. It cannot be constructed, but the field returned by `ContactSurface` can be evaluated.
  - [x] Determine policy for constructing in python. #17799

#### Mesh APIs

`PolygonSurfaceMesh`, `TriangleSurfaceMesh`, and `VolumeMesh` have a number of parallel APIs (those related to their mesh-ness). They are predominantly bound for `PolygonSurfaceMesh`, but sporadically for the others. These represent the least common denominator across all three classes. The following APIs should all be added to maintain parity across mesh types. An alternative method to maintain parity would be to omit them for all mesh types (so, it should be removed from `PolygonSurfaceMesh` and some documentation should communicate the reason for the omission).

- `TriangleSurfaceMesh::element()`
- `VolumeMesh::element()`
- `TriangleSurfaceMesh::vertex()`
- `VolumeMesh::vertex()`
- `TriangleSurfaceMesh::num_vertices()`
- `VolumeMesh::num_vertices()`
- `TriangleSurfaceMesh::num_elements()`
- `VolumeMesh::num_elements()`
- `TriangleSurfaceMesh::Equal()`
- `VolumeMesh::Equal()`

There are also APIs common to the two surface mesh types. Again, `PolygonSurfaceMesh` has them, `TriangleSurfaceMesh` is missing them. The following should be added.

- `TriangleSurfaceMesh::area()`
- `TriangleSurfaceMesh::total_area()`
- `TriangleSurfaceMesh::face_normal()`
- `TriangleSurfaceMesh::centroid()`
- `TriangleSurfaceMesh::CalcBoundingBox()`

The following APIs are unique to the other mesh types and don't exist in `PolygonSurfaceMesh`:

- `TriangleSurfaceMesh::CalcBarycentric()`  (This method *does* exist for `PolygonSurfaceMesh`, but it can only throw, as such, probably not worth binding.)
- `VolumeMesh::CalcBarycentric()`
- `TriangleSurfaceMesh::num_triangles()`
- `TriangleSurfaceMesh::CalcCartesianFromBarycentric()`

These are two affected classes:
- [x] TriangleSurfaceMesh
     #17713 
- [x] VolumeMesh
     #17730

#### Extraneous missing APIs
- [x] `SurfaceTriangle::num_vertices()` -- this is optional. The argument in favor of this binding is to keep this struct in parallel with `SurfacePolygon`.
    #17713

#### Optional missing APIs
- `ReadObjToTriangleSurfaceMesh()` - There are two overloads for this in C++. One takes a string as the *name of the OBJ file* the other takes a `std::istream` and is the contents of the file. It might be nice to create a triangle mesh from a string OBJ in python. But this isn't a direct binding.

#### Bindings to remove

- `PolygonSurfaceMesh::TransformVertices()` (see ancillary notes below for details).
- `PolygonSurfaceMesh::ReverseFaceWinding()` (see ancillary notes below for details).

- [x] #17768

#### Ancillary notes and tasks.

There are a number of APIs that should not be bound. Typically these are functions that serve the purpose of internal utility but are `public` (in the C++) sense to facilitate invocation. The documentation should clearly indicate that they are advanced/internal and, optionally, they should be omitted from the rendered doxygen.

- `*Mesh::TransformVertices()`
- `*Mesh::CalcGradientVectorOfLinearField()`
 - `SurfaceTriangle::ReverseWinding()`
 - `SurfacePolygon::copy_to_unique()` (already marked internal, possibly also exclude from doxygen).

- [x] #17768

Finally:

 - `ContactSurface` has no constructors bound. In the bindings it says that no constructors are "bound yet". It is not clear that we *want* to bind them. It may be that the binding simply exists so that the contact results can be *observed* but not necessarily generated. We need to definitively make this decision and align the code accordingly.
 - [x] #17799

### Version

1.5

### What operating system are you using?

Ubuntu 20.04

### What installation option are you using?

compiled from source code using Bazel

**Comment by DamrongGuoy** [comment]
Done. Thank you. Close now.
