### ISSUE TITLE
Add support for macOS Ventura

### ISSUE THREAD

**Issue by svenevs** [RobotLocomotion/drake#18327]
- [x] Add PR that updates `from_source.md` and `installation.md` once we have a successful build going.
- [X] Identify the locations drake warns about unsupported OS / compiler (only a few).
    - [X] Add `"13"` to list (#19350)
    
        https://github.com/RobotLocomotion/drake/blob/f2a3f717f49dacac0c066892fa2db2342a5709d4/tools/workspace/os.bzl#L168
- [x] Fix a few build error(s) with new Xcode ([reference job log](https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-everything-release/3/consoleFull).
    - [x] ERROR: -wunusedbutset

        ```console
        [4:16:03 AM]  ERROR: /Users/admin/workspace/mac-arm-ventura-clang-bazel-experimental-everything-release/src/multibody/inverse_kinematics/BUILD.bazel:27:17: Compiling multibody/inverse_kinematics/constraint_relaxing_ik.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target //multibody/inverse_kinematics:constraint_relaxing_ik) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 401 arguments skipped)
        [4:16:03 AM]  
        [4:16:03 AM]  Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
        [4:16:03 AM]  multibody/inverse_kinematics/constraint_relaxing_ik.cc:55:7: error: variable 'step_ctr' set but not used [-Werror,-Wunused-but-set-variable]
        [4:16:03 AM]    int step_ctr = 0;
        ```

    - [x]  geometry/proximity/mesh_plane_intersection.cc:87:7 `int num_intersections = 0;`
    - [x] multibody/plant/multibody_plant.cc:2559:7 `int num_actuated_instances = 0;`
    - [x] ERROR: /Users/admin/workspace/mac-arm-ventura-clang-bazel-experimental-everything-release/src/common/symbolic/expression/BUILD.bazel:192:20: Compiling common/symbolic/expression/test/substitution_test.cc failed: (Exit 1): wrapped_clang_pp failed: error executing command (from target //common/symbolic/expression:substitution_test) external/local_config_cc/wrapped_clang_pp '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -g0 -O2 -DNDEBUG ... (remaining 143 arguments skipped)
        - error: no member named 'result_of' in namespace 'std'; did you mean 'Eigen::internal::result_of'?
        - `std::result_of` usage here [deprecated in c++17 removed in c++20](https://en.cppreference.com/w/cpp/types/result_of)
- [ ] Fix a few build warnings with new Xcode ([reference job log](https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-everything-release/3/consoleFull)).
    - [ ] `warning: unqualified call to 'std::move' [-Wunqualified-std-cast-call]` (#19380)
    - [ ] external/csdp/lib/op_at.c:9:6: warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype] (many of these kinds of warnings)
    - [ ] external/curl_internal/lib/mprintf.c:975:10: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
- [ ] Failing tests that may need further fixing / resolution:
    - [ ] FAIL: //geometry/render_vtk:internal_render_engine_vtk_test, see [job log](https://drake-jenkins.csail.mit.edu/job/mac-arm-ventura-clang-bazel-experimental-everything-release/3/consoleFull) -- this is a familiar test failure.  But CI issues cannot yet be ruled out with gpu issues.
    - [x] FAIL: //geometry/proximity:obb_test (#19371)
    - [x] FAIL: //multibody/fem:fem_solver_test (#19372)
    - [X] FAIL: //math:linear_solve_test (#19373)
    - [X] FAIL: //common/schema:transform_test (#19374)
    - [x] FAIL: //systems/primitives:symbolic_vector_system_test (#19375)
    - [x] FAIL: //solvers:nonlinear_program_test (#19376)
    - [x] FAIL: //solvers:create_constraint_test => `@hongkai-dai  via #7320`

        ```
        [ RUN      ] ParseRotatedLorentzConeConstraintTest.Test2
        unknown file: Failure
        C++ exception with description "Y is not positive semidefinite. It has an eigenvalue -7.86107358387903e-16 that is less than the tolerance -0." thrown in the test body.
        ```

        https://github.com/RobotLocomotion/drake/blob/8327b29738705689cc13265b16ac656ce0cea631/solvers/test/create_constraint_test.cc#L268-L278

    - [X] FAIL: //solvers:constraint_test (#19377)
    - [X] FAIL: //solvers:clp_solver_test (#19378)
    - [x] //multibody/benchmarks/chaotic_babyboot/MG:MG_chaotic_babyboot_test (#19379)
- [ ] Is there a way to silence the huge amount of warnings from the linker about visibility settings?  (This has been a long standing issue with macOS build logs...)
    ```
    [4:51:37 AM]  ld: warning: direct access in function 'drake::multibody::internal::MultibodyTree<drake::symbolic::Expression>::GetDefaultFreeBodyPoseAsQuaternionVec3Pair(drake::multibody::Body<drake::symbolic::Expression> const&) const' from file 'bazel-out/darwin_arm64-opt/bin/multibody/tree/libmultibody_tree_core.a(multibody_tree.pic.o)' to global weak symbol 'typeinfo for drake::multibody::Joint<drake::symbolic::Expression>' from file 'bazel-out/darwin_arm64-opt/bin/multibody/tree/libmultibody_tree_core.a(joint.pic.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
    ```
- [x] Make sure caching is turned on.
- [X] Enable drake-ci ventura detection: https://github.com/RobotLocomotion/drake-ci/pull/221
- [X] ~~x86 vSphere images can be built at any time, noting that we should select Xcode 14.1 for Ventura.~~
    - x86 ventura virtualization is supposedly possible but we choose not to take that adventure
- [X] arm64 orka CI images built 2023-05-04
    - [X] bottle vtk@9.1.0 for ventura arm64

@jwnimmer-tri please let us know how to proceed / priority of this ticket (specifically, if we want to do them separately or keep x86 on hold until arm64 is available).

CC @BetsyMcPhail 

NOTE: a full local build on Ventura on an arm64 macmini (tri-macmini-01) using Xcode 14.1 (Monterey CI is currently 14.0.1) indicated that all of drake can compile.  Tests need to be rerun there (gurobi license server connection issues), more results to be posted here.

**Comment by jwnimmer-tri** [comment]
The first goal should be x86 only.  It's fine to defer arm64 support until we have Orka remote caching working.

**Comment by jwnimmer-tri** [comment]
Update from meeting: because we ship releases on Monterey, we can err on the side of most CI jobs still being on on Monterey.  We just want a few Ventura jobs to sanity-check that all tests pass.  Possibly just 1 bazel release + 1 bazel everything release would suffice.

**Comment by jwnimmer-tri** [comment]
Also once we make progress here, we should fix https://drake.mit.edu/installation.html and https://drake.mit.edu/from_source.html to mention Ventura.  (It's somewhat embarrassing that we can't claim that yet.)

**Comment by jwnimmer-tri** [comment]
> The first goal should be x86 only.

I take it back.  Let's not do anything on vSphere.

If we can get even an arm release build or few going, that's a great start.

**Comment by svenevs** [comment]
https://drake-jenkins.csail.mit.edu/view/Mac%20Ventura/

We have ventura arm64 support.  13.3.1, xcode 14.3 is what is running in CI.

**Comment by jwnimmer-tri** [comment]
Known TODO:
- The os.bzl is spewing a warning (b/c there was no CI); now that there is CI, remove the warning.
- Update docs stating support for Ventura.
- A few build error(s) with new Xcode.

**Comment by svenevs** [comment]
@jwnimmer-tri I updated the checklist after scraping the log, I think I got most of them.

1. For the `std::move` thing, I tried to add `--copt='-Werror' --cxxopt='-Werror'` to get it to crash but that doesn't appear right.  Is there an easy way to force `-Werror`?  I see `-Werror` in other places, but can't trigger error for this warning specifically.
2. How much do we care about warnings coming from externals.  We've got `move` vs `std::move` warning, `curl` using unsafe `sprintf`, and a lot of `warning: a function declaration without a prototype is deprecated in all versions of C and is not supported in C2x [-Wdeprecated-non-prototype]` from C deps going on.
3. Once the easier fish have been fried and the build logs become more manageable, most of the test failures are related to solver tolerances so it would probably be best to punt back to TRI after we can get things cleaned up a bit first.

**Comment by jwnimmer-tri** [comment]
(1) See [drake_cc.bzl](https://github.com/RobotLocomotion/drake/blob/master/tools/skylark/drake_cc.bzl), probably the `APPLECLANG_VERSION_SPECIFIC_FLAGS` will be the right place to say `-Werror=unqualified-std-cast-call`.

Separate from PR'ing that Werror change, we anyway should PR the code fixes to remove `using std::move;` throughout Drake.  I could do that, if it helps?

(2) Generally externals should mute all warnings, so `copts = ["-w"],` in their BUILD rule(s).

**Comment by svenevs** [comment]
Ok thank you. With an error flag it's easy for me to whittle them down, but if you would rather do it I certainly won't stop you.  I'd like to fix that before asking people to look at solvers issues since currently the build log is really cluttered.

I'll be able to do that tomorrow.

**Comment by jwnimmer-tri** [comment]
I'll do the `std::move` today, then.  I don't need the error flag, it's really just perl pie to delete `using std::move;`.  Every single time that line appears it's wrong, and should be deleted.  That *should* get all of the warnings gone.  I guess anything that's remaining you can follow-up on tomorrow.

**Comment by jwnimmer-tri** [comment]
All but two files worth of `std::move` is fixed.  In your PR that adds the `-Werror...` flag for it, we can fix those remaining two files.

As of the PRs shown in the timeline above, I think all of the build **errors** are fixed.

I haven't looked at the tests yet.  For tolerancing failures, general procedure would be to open one PR per test that bumps the tolerance up so that it passes, and then assign the PR feature review the test-owner.  They can either LGTM it, or push whatever other fix they prefer instead.

**Comment by jwnimmer-tri** [comment]
As far as warnings -- we can move CI into Production (and advertise official support in our docs) even with warnings.  We can file follow-up tickets to stomp out any specific remaining warnings that seem worth fighting.

**Comment by svenevs** [comment]
- Tolerance PRs are up and assigned, except for `//solvers:create_constraint_test` (first post edited)
- Warning against unsafe std call ended up being a bit more involved, #19380
- Remaining: vtk test

**Comment by jwnimmer-tri** [comment]
All but two tests are passing now:

(1) The VTK rendering failure.  I don't plan on investigating this one myself.  I'll most likely disable it on Ventura+Arm and leave it ticketed as a follow-up.

(2) A solvers constraint one.  It's a tolerancing problem but the solution isn't yet obvious to me.  I'll keep investigating.

**Comment by jwnimmer-tri** [comment]
The last two PRs are filed.  Once they merge, I think we should be ready to move into Production.

**Comment by BetsyMcPhail** [comment]
It turns out that caching is already turned on for release jobs with existing logic in drake-ci scripts (https://github.com/RobotLocomotion/drake-ci/blob/59c36cca473de1a155c7be1aa2b18394f79965c5/driver/environment.cmake#L140).

The debug jobs caching can be sorted out as part of #19341

**Comment by BetsyMcPhail** [comment]
Ventura jobs have been moved to production.

**Comment by jwnimmer-tri** [comment]
This is done now, with a non-critical few things filed as follow-ups:
- https://github.com/RobotLocomotion/drake/issues/19424
- https://github.com/RobotLocomotion/drake/pull/19380

If there are more things still remaining, please open new issues.
