### ISSUE TITLE
SpatialInertia factory functions for primitive shapes.

### ISSUE THREAD

**Issue by mitiguy** [RobotLocomotion/drake#18416]
Implement SpatialInertia factory functions for primitive shapes.
- [x] "Prototype PR #18407" that creates a partial fit, form, function for a SpatialInertia factory method for a uniform-density solid box.  Although this is a "prototype PR", it is intended to be merged into master, albeit with a delay on  Python bindings until other primitive shapes also have C++ code.  This "prototype PR" provide a template for the function name, parameter names, documentation, and use in C++.   PR #18407 prototypes the name, unit test, and utility of the newly proposed function.   
1. There were several candidate names including MakeSolidBox(), SolidBox(), SolidBoxViaDensity(), SolidBoxFromDensity() and the winning candidate SolidBoxWithDensity().
2. There were two candidate ways to unit test this function.  The test implemented in the final commit of PR #18407 is shorter and clearer than the initial test (which was correct but overly laborious).  
3. The utility of SolidBoxWithDensity() was investigated by replacing code in geometry_spatial_inertia.c with its shorter call to SolidBoxWithDensity().  Similarly, a few other call sites demonstrated that SolidBoxWithDensity() has utility in more than one part of Drake's C++ code.
- [x] PR #18483 implements all the primitive shapes that are used in geometry_spatial_inertia.cc (SolidCylinderWithDensity(), SolidBoxWithDensity(), SolidCapsuleWithDensity(), SolidEllipsoidWithDensity().
- [x] Create PR to update the documentation and signatures of factories of primitive shapes in unit_inertia.h.  For example, update the signature of a cylinder and capsule which have a unit vector direction that is implied through a default argument or hard-coded and unchangeable.  Update documentation in unit_inertia.h to reflect the improved argument names in spatial_inertia.h.  Deprecate Python bindings.  Note this may be a "breaking change". 
- [x] PRs to implement the remaining primitive shapes used in unit_inertia.cc include PR #18864, PR #18865, PR #18866, PR #18889, PR #18891, PR #18950.
- [x] PR #18618 implements SolidTetrahedronWithDensity() in spatial_inertia.cc and SolidTetrahedron() in unit_inertia.cc.  
- [ ] NOT DONE, BUT MAYBE NOT NEEDED.  Update geometry_spatial_inertia.cc with calls to tetrahedron in unit_inertia.cc and spatial_inertia.cc.  Code that Sean found for calculating mass properties (volume, centroid, inertia) seems to be working. 
- [x] PR #19134 to Python bind many of the SpatialInertia factory methods for primitive shapes. These include: SolidBoxWithDensity(), SolidCubeWithDensity(),  SolidCapsuleWithDensity(), SolidCapsuleWithDensityAboutEnd(), SolidCylinderWithDensity(), SolidCylinderWithDensityAboutEnd(), SolidEllipsoidWithDensity(), SolidSphereWithDensity(), HollowSphereWithDensity(), ThinRodWithMass(), ThinRodWithMassAboutEnd(), 
- [x] PR #19141 for SpatialInertia factory method SolidBoxWithMass() as a prototype for remaining "WithMass() SpatialInertia factory methods.  Opportunistically replace UnitInertia::SolidBox() methods as sensible.
- [x] PRs for SpatialInertia factory "WithMass()" methods and opportunistically replace calls to UnitInertia methods, include PR #19171, PR #19268, PR #19737, PR #19803 
- [x] Opportunistically, replace calls to the SpatialInertia constructor that uses density and a UnitInertia factory method for primitive shapes with the equivalent new SpatialInertia factory functions.

**Comment by SeanCurtis-TRI** [comment]
Perhaps "Create a PR" is not what the checklist should be. It's not the creation of the PR that is of interest; it's the introduction of code into master. So, perhaps, it would be better to rephrase it and "uncheck" the current box.

**Comment by mitiguy** [comment]
This issue was addressed in multiple PRs and now seems to be able to be closed.
