### ISSUE TITLE
[multibody] MultibodyTree performance improvement epic

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#18442]
Per discussion with @amcastro-tri, we would like to perform some major surgery on MultibodyTree to achieve two goals:
- Make it produce the same results as fast as possible, with 10X as a target (primary goal)
- Clean up the code with an eye to making some of its API public
- Substantially reduce compile time

There is some apparent low-hanging fruit to be exploited:
- [ ] Combine Mobilizer & BodyNode into a single class (e.g. MobilizedBodyNode) with templatized implementations permitting common operations to be performed with only a single virtual function call. The executed code should use only fixed-size matrices.
- [ ] Reparameterize MbTree to work with frames chosen for efficiency. In general this means the effective body origins will be moved to the inboard joint frame (Bo==Mo) and aligned so that the H matrices for common joints have only a single non-zero element. (This would be hidden from users who would only see things in their original frames.)
- [ ] Provide MobilizedBodyNode specializations that provide optimal handling of (a) revolute, (b) prismatic, and (c) free joints that have simple H matrices after the above processing.
- [ ] Move template function definitions into .cc files and explicitly instantiate there to improve compile times. MultibodyElement may be the worst offender currently.

Performance work should be backed by timings taken on the same computers. Cassie bench's mass matrix, inverse dynamics, and forward dynamics make good targets.

**Comment by sherm1** [comment]
[Capturing a 1:1 discussion w/Alejandro]

Thoughts on how to present multibody modeling elegantly

1. User defines Plant structure via Links and Joints, producing a directed (parent->child) graph, plus some disconnected Links. Call this **LinkJointGraph**.
2. At Finalize() (or any other time by request) we produce a spanning tree model of the LinkJointGraph, with depth-first coordinate assignments. Call this **SpanningTreeModel** (or some better name). Should have an API for forest info.
3. Augment the Plant structure with additional elements (added free Joints, shadow Links, added constraints) to use as a uniform interface to those elements for users who care (we already do this with floating Joints). The augmented elements are easily removed when we remodel.
4. Use **MultibodyKernel** for the tight, efficient Featherstone-ish thing that only takes basic numerical data structures and computes kinematics, inverse/forward dynamics, etc. Figure out how to make that public
      - no context!
      - no systems::

Both LinkJointGraph and SpanningTreeModel have nice public APIs for users to query.

MultibodyTree should then be thought of more like MultibodyPlantImpl (consider renaming). Its job is to implement an efficient computational representation of the SpanningTreeModel (which essentially replaces the MultibodyTopology stuff), creating a MultibodyKernel devoted entirely to fast computation.

Here is a sketch of a LinkJointGraph with a loop being modeled as a spanning tree and an augmented LinkJointGraph:

![image](https://user-images.githubusercontent.com/4088016/227291801-104443dc-c25a-4256-bcb7-11910b8e5665.png)
