### ISSUE TITLE
GCSTrajectoryOptimization can reproduce the examples from the paper

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#19308]
https://arxiv.org/abs/2205.04422

@wrangelvid is making great progress!  We agreed to make this issue to track the status.

Still TODO:
- [x] Time costs (#19301)
- [x] Velocity constraints on `Subgraphs` (#19334)
- [x] Velocity constraints on `EdgesBetweenSubgraphs` (#19357)
- [x] Energy Costs
- [x] Improve rounded problem in `GraphOfConvexSets` (#19816)
- [x] Remove zero columns from constraints added to the graph (#19444)
- [x] Parallelize intersection checks in `AddRegions()` (#19337)

**Comment by RussTedrake** [comment]
Update: I've ported @wrangelvid 's latest and greatest uav example into the underactuated repo, where I will continue to nurture/maintain it.  https://github.com/RussTedrake/underactuated/blob/master/book/trajopt/gcs_quadrotor.ipynb .  We're just missing the energy costs (really derivative costs) now to implement the minimum-snap objective.  Great work @wrangelvid ! 🎉

**Comment by RussTedrake** [comment]
#21810 has landed.  @wrangelvid ... shall we consider this complete and close the issue?

**Comment by wrangelvid** [comment]
> #21810 has landed.  @wrangelvid ... shall we consider this complete and close the issue?

Awesome. Looks good to me!
