### ISSUE TITLE
Transform Between HPolyhedron and VPolytope when Sets Aren't Full Dimensional

### ISSUE THREAD

**Issue by cohnt** [RobotLocomotion/drake#19717]
When transforming back and forth between representing a set as an HPolyhedron and a VPolytope, Drake makes a call to QHull. However, when this set is not full-dimensional, QHull throws an error (in both directions). QHull provides the following suggestion:

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - **determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.**
  - add one or more points to make the input full dimensional.

I'm planning to implement the third option, and am creating this issue to track progress across multiple PRs. My plan is the following:
 - [x] Check if a ConvexSet is empty. (Sometimes, this can be done in O(1) time. Others, it may require solving an optimization problem.) #19716
 - [x] Clarify the distinction between empty and nonempty zero-dimensional convex sets. Discussed further in #19723.  #19732
 - [x] Compute a feasible point within an arbitrary ConvexSet. (Sometimes, this can be done in O(1) time. Others, it may require solving an optimization problem.) #19804
     - [x] Add improved feasible point methods for certain ConvexSet subclasses. #19824
 - [x] Create a new subclass of ConvexSet, "AffineSubspace", described as a basis plus a translation. #19828
     - [x] Implement checks for containment and equivalence. #19850
     - [x] Implement methods for projection, projection to local coordinates, and lifting from local coordinates to ambient space. #19851
 - [x] Add constructor to AffineSubspace to compute the affine hull of another convex set. #19864
 - [x] When converting between HPolyhedron and VPolytope, if QHull throws an error due to the dimension, handle it. Compute the affine hull, change coordinates onto the flat so that it is full dimensional, perform the QHull computations, and then transform back to the original coordinate system.
     - [x] VPolytope -> HPolyhedron. #19979
     - [x] HPolyhedron -> VPolytope. #20001

VPolytope to HPolyhedron Error (not enough points):
```
import numpy as np
from pydrake.all import HPolyhedron, VPolytope
v = VPolytope(np.array([[1, 0], [2, 0]]).T)
h = HPolyhedron(v)
```
Output: `RuntimeError: QH6214 qhull input error: not enough points(2) to construct initial simplex (need 3)`

VPolytope to HPolyhedron Error (not full dimensional):
```
import numpy as np
from pydrake.all import HPolyhedron, VPolytope
v = VPolytope(np.array([[1, 0], [2, 0], [3, 0]]).T)
h = HPolyhedron(v)
```
Output: `RuntimeError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)`

HPolyhedron to VPolytope Error (not full dimensional):
```
import numpy as np
from pydrake.all import HPolyhedron, VPolytope
A = np.array([
  [1, 0],
  [-1, 0],
  [0, 1],
  [0, -1]
])
b = np.array([1, 0, 0, 0])
h = HPolyhedron(A, b)
v = VPolytope(h)
```
Output: `RuntimeError: QH6023 qhull input error: feasible point is not clearly inside halfspace`

**Comment by cohnt** [comment]
Now that #20001 has merged, you can freely convert between sub-dimensional VPolytopes and HPolyhedra, so I'm closing the issue.
