### ISSUE TITLE
macOS Sonoma (14) support / CI

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#20339]
**Is your feature request related to a problem? Please describe.**

Apple has released macOS Sonoma (14) a couple weeks ago.  Drake should officially (https://drake.mit.edu/installation.html) support it, which means testing and CI coverage.

**Describe the solution you'd like**

Add Sonoma builds to CI, get them passing, elevate to Production, then update our docs & releases.

Since we only [support](https://drake.mit.edu/stable.html#os-support) the two most recent versions of macOS, that means (mostly) dropping Monterey.  However, we'll leave alone macOS Monterey (12) x86 CI for now.

Tasks:
- [x] Drake / DJJ: Switch our packaging jobs and release process to use Ventura as the minimum.
    - Note: this includes "packaging", "staging", and "wheel" jobs. 
    - [X] Jenkins: https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/95
    - [X] drake-ci: https://github.com/RobotLocomotion/drake-ci/pull/252
    - [X] Update download_release_candidate to download the new arm64 wheel (#20520).
- [X] Docs: Remove macOS Monterey (12) arm64 from our list of supported platforms.  Likewise update the release playbook. (#20511)
- [X] DEE: Bump from macOS 12 to to macOS 13. (https://github.com/RobotLocomotion/drake-external-examples/pull/275)
- [ ] DJJ: Figure out which Monterey jobs to switch over to Ventura (either permanently, or only until we have Sonoma at which point they move up again) and switch them over. (https://github.com/RobotLocomotion/drake/issues/20339#issuecomment-1807160642)
    - [X] Switch over cache-server health check jobs (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/96)
        - [ ] Note: these jobs aren't really mentioned anywhere in the docs (e.g., `buildcop.md`).  Should the be?
    - [X] Asan jobs (monterey -> ventura) (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/97)
    - [x] mac-arm-cmake-nightly
        - [X] Remove monterey (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/98)
        - [x] Add sonoma
   - [x] mac-arm-bazel-nightly
       - [X] Remove monterey (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/99)
   - [X] mac-arm defaults
       - [X] Remove monterey (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/100)
       - [X] Add sonoma defaults [minus production] (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/101)
       - :x: Warning for macOS 15 update: that PR [accidentally added a `mac-arm-sonoma-unprovisioned-clang-bazel-nightly-release` production job](https://drakedevelopers.slack.com/archives/C270MN28G/p1700321305928319) :see_no_evil: 
    - [x] Add experimental (only) wheel builds (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/102) (note: this was added to test a local problem, usually we don't have macOS N+1 and maybe should delete)
- [X] Switch to two ventura and one monterey runner.
    - [X] `orka` backend: `orka node tag/untag`, and `deploy` the ventura images.
    - [X] After deployed, jenkins plugin, change the number of available runners [in the jenkins cloud advanced settings](https://drake-jenkins.csail.mit.edu/manage/cloud/) as well as move the node mapping from one to the other [deleted mapping for arm-mini-003 from monterey cloud, added the same mapping to the ventura cloud].
- [X] CI: Turn off macOS Monterey (12) arm64.
- [X] CI: Prepare macOS Sonoma (14) arm64 base images / Orka stuff.  Use XCode 15.
- [X] Rebalance: two ventura, one sonoma runner:
    - [X] `orka` backend: tag and deploy.
    - [X] Jenkins plugin: reconfigure Monterey cloud to be Sonoma (change labels etc), confirm node mapping.
- [X] DJJ: Add the suite of Experimental jobs for Sonoma to drake-jenkins-jobs.  Launch them all to see what failures we have (https://github.com/RobotLocomotion/drake-jenkins-jobs/pull/101)
- [x] Enable builds to run via jenkins (https://github.com/RobotLocomotion/drake-ci/pull/254)
- [x] Drake: Open PRs to fix any Sonoma failures.
- [x] DJJ: Once the Sonoma jobs are passing, start to promote them to Production.
- [ ] Docs: Add Sonoma to our support matrix.  Likewise update the release playbook.

**Comment by BetsyMcPhail** [comment]
Reminder to myself to not forget to switch the packing job's "publish" flag from Monterey to Ventura in drake-ci: https://github.com/RobotLocomotion/drake-ci/blob/92bfabe99de6fcdd269b7aa654891ab0f8d4e214/driver/environment.cmake#L216

**Comment by jwnimmer-tri** [comment]
In #20340 we added the ability to test the Packaging and Wheel jobs on Ventura.  Both of those passed (see logs for [Wheel](https://drake-jenkins.csail.mit.edu/view/Wheel/job/mac-arm-ventura-unprovisioned-clang-wheel-experimental-release/) and [Packaging](https://drake-jenkins.csail.mit.edu/view/Packaging/job/mac-arm-ventura-unprovisioned-clang-bazel-experimental-packaging/)).

**Comment by jwnimmer-tri** [comment]
I suppose let's say that Drake v1.22.0 (ETA next Monday) will still keep Monterey on all fronts, so let's not actually ditch any Monterey jobs yet.  After the release happens, we can start shutting things off.

**Comment by jwnimmer-tri** [comment]
The release has been shipped, so you have a green light for turning off Monterey (on arm).

**Comment by jwnimmer-tri** [comment]
The goal should be to finish the first three items (mac arm packaging builds, docs, and drake-external-examples) before the next release (mid-November).

**Comment by BetsyMcPhail** [comment]
While working on the first bullet point, I noticed that the Mac "staging-packaging" jobs have never been run and are not mentioned in the release playbook. Should these jobs be removed?

**Comment by jwnimmer-tri** [comment]
I can't say for certain without chasing down a few details first, but I'd guess that maybe @mwoehlke-kitware's work to do https://github.com/RobotLocomotion/drake/issues/18300 will end up needing them after all?

**Comment by BetsyMcPhail** [comment]
I'll leave them for now!

**Comment by mwoehlke-kitware** [comment]
Yes, #18300 will require packages built by staging jobs.

**Comment by svenevs** [comment]
@mwoehlke-kitware I may have made a mistake updating the jenkins yaml and deleted jobs you were using.  If so, let us know and we can restore it or use the ventura flavor now possibly?  After I made my change, [linux-jammy-clang-bazel-continuous-everything-address-sanitizer](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-jammy-clang-bazel-continuous-everything-address-sanitizer/) and [linux-jammy-clang-bazel-continuous-leak-sanitizer](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/linux-jammy-clang-bazel-continuous-leak-sanitizer/) were showing up as never having been run before (right after I deployed jenkins)... Sorry :/

@jwnimmer-tri after switching the load balance between monterey and ventura jobs was mostly even, with the cache server health check job being the tie breaker.  We went ahead and switched that over and are rebalancing to one monterey and two ventura runners.  [Posted an FYI in slack just in case we have issues](https://drakedevelopers.slack.com/archives/C270MN28G/p1699570110166109).

**Comment by svenevs** [comment]
> DJJ: Figure out which Monterey jobs to switch over to Ventura (either permanently, or only until we have Sonoma at which point they move up again) and switch them over.

This is where we are currently at.  I reached out to MacStadium to figure out if Sonoma is supported yet, it does not appear to be and I also get the impression we will need another orka upgrade first.  While that may stall this ticket for a while, these are the last jobs on monterey arm being considered (`curl https://drake-jenkins.csail.mit.edu/api/json?tree=jobs[name] | jq '.jobs[].name' | /bin/grep monterey | /bin/grep -v x86`):

- Continuous:
    - `mac-arm-monterey-clang-bazel-continuous-release`
- Nightly:
    - `mac-arm-monterey-clang-bazel-nightly-debug`
    - `mac-arm-monterey-clang-bazel-nightly-everything-address-sanitizer`
    - `mac-arm-monterey-clang-bazel-nightly-everything-release`
    - `mac-arm-monterey-clang-cmake-nightly-everything-release`
    - `mac-arm-monterey-clang-cmake-nightly-release`
    - `mac-arm-monterey-unprovisioned-clang-bazel-nightly-release`
- Experimental:
    - `mac-arm-monterey-clang-bazel-experimental-address-sanitizer`
    - `mac-arm-monterey-clang-bazel-experimental-debug`
    - `mac-arm-monterey-clang-bazel-experimental-everything-address-sanitizer`
    - `mac-arm-monterey-clang-bazel-experimental-everything-debug`
    - `mac-arm-monterey-clang-bazel-experimental-everything-release`
    - `mac-arm-monterey-clang-bazel-experimental-release`
    - `mac-arm-monterey-clang-cmake-experimental-everything-release`
    - `mac-arm-monterey-clang-cmake-experimental-release`
    - `mac-arm-monterey-unprovisioned-clang-bazel-experimental-everything-release`
    - `mac-arm-monterey-unprovisioned-clang-bazel-experimental-release`
    - `mac-arm-monterey-unprovisioned-clang-cmake-experimental-everything-release`
    - `mac-arm-monterey-unprovisioned-clang-cmake-experimental-release`

So, before we just switch them all to monterey blindly, do we know which ones we want to be sonoma long term?

**Comment by mwoehlke-kitware** [comment]
@svenevs, these are the staging packages we need:
```
# Wheels.
f"drake-{version[1:]}-cp38-cp38-manylinux_2_31_x86_64.whl",
f"drake-{version[1:]}-cp39-cp39-manylinux_2_31_x86_64.whl",
f"drake-{version[1:]}-cp310-cp310-manylinux_2_31_x86_64.whl",
f"drake-{version[1:]}-cp311-cp311-manylinux_2_31_x86_64.whl",
f"drake-{version[1:]}-cp311-cp311-macosx_12_0_x86_64.whl",
f"drake-{version[1:]}-cp311-cp311-macosx_12_0_arm64.whl",
# Deb packages.
f"drake-dev_{version[1:]}-1_amd64-focal.deb",
f"drake-dev_{version[1:]}-1_amd64-jammy.deb",
# Tarballs.
f"drake-{version[1:]}-focal.tar.gz",
f"drake-{version[1:]}-jammy.tar.gz",
f"drake-{version[1:]}-mac.tar.gz",
f"drake-{version[1:]}-mac-arm64.tar.gz",
```

AFAICT we still have jobs for all of those? (IIUC, the non-wheel Ubuntu jobs should both generate one each `.deb` and `.tar.gz`, while all Ubuntu wheels are generated by one job.)

**Comment by svenevs** [comment]
@mwoehlke-kitware staging now has [mac-arm-ventura-unprovisioned-clang-wheel-staging-release](https://drake-jenkins.csail.mit.edu/view/Staging/job/mac-arm-ventura-unprovisioned-clang-wheel-staging-release/) instead of `monterey`.  So I think the arm64 wheel is going to give you `macosx_13_0` now (not `12_0`).  I'm about to open a PR, we missed this in the first pass.

AFAICT you never staged any wheels for 0.99, [staging artifacts end up here](https://s3.console.aws.amazon.com/s3/buckets/drake-packages?region=us-east-1&prefix=drake/staging/&showversions=false).  So (next week it seems) if you could stage the rest of the jobs, then we'll have the artifacts needed for you and know if that's the only change that the unrelated work here broke for you :crossed_fingers:

**Comment by jwnimmer-tri** [comment]
macOS ARM CI policy:

(1) The "health check" can be whatever.  I guess just a single macOS version?

(2) The nightly packaging and nightly wheel builds only run on the oldest supported macOS version for the given architecture.  (This is already up-to-date with Sonoma as of https://github.com/RobotLocomotion/drake-ci/pull/252.)

(3) The "release build from scratch" jobs (unprovisioned nightly) should be run on every supported macOS:

* mac-x86-monterey-unprovisioned-clang-bazel-nightly-release
* ~mac-arm-monterey-unprovisioned-clang-bazel-nightly-release~ (<== remove)
* mac-arm-ventura-unprovisioned-clang-bazel-nightly-release	
* __mac-arm-sonoma-unprovisioned-clang-bazel-nightly-release__ (<== to be added)

(4) The only thing in continuous should be the typical incremental release build, run on every supported macOS:

* mac-x86-monterey-clang-bazel-continuous-release		
* ~mac-arm-monterey-clang-bazel-continuous-release~ (<== remove)
* mac-arm-ventura-clang-bazel-continuous-release
* __mac-arm-sonoma-clang-bazel-continuous-release__ (<== to be added)

(5) The supplemental release-build nightlies (cmake, everything) should run on every supported macOS:

* ~mac-arm-monterey-clang-bazel-nightly-everything-release~ (<== remove)
* ~mac-arm-monterey-clang-cmake-nightly-everything-release~ (<== remove)
* ~mac-arm-monterey-clang-cmake-nightly-release~ (<== remove)
* mac-arm-ventura-clang-bazel-nightly-everything-release
* mac-arm-ventura-clang-cmake-nightly-everything-release
* mac-arm-ventura-clang-cmake-nightly-release
* __mac-arm-sonoma-clang-bazel-nightly-everything-release__ (<== to be added)
* __mac-arm-sonoma-clang-cmake-nightly-everything-release__ (<== to be added)
* __mac-arm-sonoma-clang-cmake-nightly-release__ (<== to be added)

(6) The extra-testing nightlies (debug) should run on the same macOS as the packaging jobs, i.e., the oldest one:

* ~mac-arm-monterey-clang-bazel-nightly-debug~ (<== remove)
* ~mac-arm-monterey-clang-bazel-nightly-everything-address-sanitizer~ (<== remove)
* __mac-arm-sonoma-clang-bazel-nightly-debug__ (<== to be added)
* __mac-arm-sonomaclang-bazel-nightly-everything-address-sanitizer__ (<== to be added)

If we end up over capacity, part (5) would be the one we could prune a bit.

**Comment by svenevs** [comment]
@jwnimmer-tri I went as closely to that as we could, given how the yaml is setup.  It did resurface that there is a note in there saying we would prefer to run an asan job on mac-arm but do not currently.  Something worth reconsidering.

I have deleted all the monterey jobs as of those four PRs, both jenkins and https://github.com/RobotLocomotion/drake/tree/jenkins-jobs-experimental do not reveal any `mac-arm-monterey`.  For right now I'm calling it a night, and am going to make us a third ventura runner after deploying those images (so I can delete the monterey ones).

We seem to have a path forward with Sonoma, but it seems we may also need to schedule an orka update as well.  Will continue tomorrow.

**Comment by svenevs** [comment]
Sonoma is alive in CI, not all configurations but a handful of jobs.  The first two full builds:

- https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-everything-release/3/consoleFull
- https://drake-jenkins.csail.mit.edu/job/mac-arm-sonoma-clang-bazel-experimental-everything-debug/3/consoleFull

There are new views, I'm going to launch the remaining ones and more results will come back in time (there is only one sonoma machine so that may take some time).

**Note**: we should see if disk space is actually going to be a problem.  May need to add some more experimental builds, but AFAICT we don't need to deal with `orka image resize` to go from 90GB to 200GB anymore.  Since the debugging symbols got nuked.

The actual reason this is being tested is because `orka image resize` was failing, so I decided to just see what the 90G images could do.  Because if we do have enough space, we can actually get all the images on all the runners.

1. Removes development time for image building.
2. The previous limit was to fit 2 x 200GB images on a node.  So we will be able to fit 4 x 90GB.  Meaning all three CI runners become available for everything, and we can stop needing to worry about balancing the load and schedules between ventura and sonoma.

To be continued...

**Comment by BetsyMcPhail** [comment]
I confirmed with Stephen that the orka setup is ready for us to create the remaining Sonoma jobs. Summarizing from [above](https://github.com/RobotLocomotion/drake/issues/20339#issuecomment-1807160642) and the current Jenkins state, there are a few Sonoma jobs that still need to be created (in the list below, all jobs with a link exist in Jenkins). 

**continuous**
- [mac-arm-sonoma-clang-bazel-continuous-non-production-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-bazel-continuous-non-production-release/)

**nightly**
- [mac-arm-sonoma-unprovisioned-clang-bazel-nightly-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-nightly-release/)
- mac-arm-sonoma-clang-bazel-nightly-everything-release (non-production)
- mac-arm-sonoma-clang-cmake-nightly-everything-release (non-production)
- [mac-arm-sonoma-clang-cmake-nightly-non-production-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-cmake-nightly-non-production-release/)
- mac-arm-sonoma-clang-bazel-nightly-debug (non-production)
- mac-arm-sonoma-clang-bazel-nightly-everything-address-sanitizer (non-production)

**experimental**
- [mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-release/)
- [mac-arm-sonoma-clang-bazel-experimental-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-bazel-experimental-release/)
- [mac-arm-sonoma-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-bazel-experimental-everything-release/)
- [mac-arm-sonoma-clang-cmake-experimental-everything-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-cmake-experimental-everything-release/)
- [mac-arm-sonoma-clang-cmake-experimental-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-cmake-experimental-release/)
- [mac-arm-sonoma-clang-bazel-experimental-debug](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-bazel-experimental-debug/)
- mac-arm-sonoma-clang-bazel-experimental-everything-address-sanitizer

**already exist but not on list**
- [mac-arm-sonoma-clang-bazel-experimental-everything-debug](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-bazel-experimental-everything-debug/)
- [mac-arm-sonoma-unprovisioned-clang-bazel-experimental-everything-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-bazel-experimental-everything-release/)
- [mac-arm-sonoma-unprovisioned-clang-cmake-experimental-everything-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-cmake-experimental-everything-release/)
- [mac-arm-sonoma-unprovisioned-clang-cmake-experimental-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-cmake-experimental-release/)
- [mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma%20Unprovisioned/job/mac-arm-sonoma-unprovisioned-clang-wheel-experimental-release/)

**Comment by BetsyMcPhail** [comment]
The remaining non-production jobs (see previous comment) have been created in Jenkins.  I will monitor these jobs for the next few days and then we can move them into production.

**Comment by BetsyMcPhail** [comment]
Most of the nightly Sonoma jobs ran without issue. Several tests are failing on [mac-arm-sonoma-clang-bazel-nightly-non-production-everything-address-sanitizer](https://drake-jenkins.csail.mit.edu/view/Mac%20Sonoma/job/mac-arm-sonoma-clang-bazel-nightly-non-production-everything-address-sanitizer/1/) .

**Comment by jwnimmer-tri** [comment]
Okay, executive decision -- drop all ASan builds on all macs.  Moving forward, ASan in CI will be Ubuntu-only.

**Comment by BetsyMcPhail** [comment]
> Okay, executive decision -- drop all ASan builds on all macs. Moving forward, ASan in CI will be Ubuntu-only.

Works for me! I will make the update in Jenkins.

**Comment by BetsyMcPhail** [comment]
Sonoma jobs have been moved to production. The only item remaining is the doc update, opening a PR momentarily.
