### ISSUE TITLE
Fix all cpplint warnings on master

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#2064]
I figure having an issue checklist for cpplint compliance might be good, so here goes:
- [x] build/class
- [x] build/c++11
- [x] build/deprecated
- [x] build/endif_comment
- [x] build/explicit_make_pair
- [x] build/forward_decl
- [x] build/header_guard
- [x] build/include
- [x] build/include_alpha
- [x] build/include_order (tracked separately #2269)
- [x] build/include_what_you_use (tracked separately #2270)
- [x] build/namespaces (tracked separately #2271)
- [x] build/printf_format
- [x] build/storage_class
- [x] legal/copyright (tracked separately #1805)
- [x] readability/alt_tokens
- [x] readability/braces
- [x] readability/casting (tracked separately #2272)
- [x] readability/check
- [x] readability/constructors
- [x] readability/fn_size
- [x] readability/function
- [x] readability/inheritance
- [x] readability/multiline_comment
- [x] readability/multiline_string
- [x] readability/namespace (tracked separately #2273)
- [x] readability/nolint
- [x] readability/nul
- [x] readability/strings
- [x] readability/todo
- [x] readability/utf8
- [x] runtime/arrays
- [x] runtime/casting
- [x] runtime/explicit
- [x] runtime/int
- [x] runtime/init
- [x] runtime/invalid_increment
- [x] runtime/member_string_references
- [x] runtime/memset
- [x] runtime/indentation_namespace
- [x] runtime/operator
- [x] runtime/printf
- [x] runtime/printf_format
- [x] runtime/references (tracked separately #2274)
- [x] runtime/string
- [x] runtime/threadsafe_fn
- [x] runtime/vlog
- [x] whitespace/blank_line
- [x] whitespace/braces
- [x] whitespace/comma
- [x] whitespace/comments
- [x] whitespace/empty_conditional_body
- [x] whitespace/empty_loop_body
- [x] whitespace/end_of_line
- [x] whitespace/ending_newline
- [x] whitespace/forcolon
- [x] whitespace/indent
- [x] whitespace/line_length
- [x] whitespace/newline
- [x] whitespace/operators
- [x] whitespace/parens
- [x] whitespace/semicolon
- [x] whitespace/tab
- [x] whitespace/todo

**Comment by jwnimmer-tri** [comment]
I've broken out the few remaining warnings into their own tickets, in order to share the work, and in order to better discuss resolutions to each kind of warning (because some have slightly less obvious answers).
