### ISSUE TITLE
Support .gltf with external references

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#20932]
(Expanded from #20152.)

**Is your feature request related to a problem? Please describe.**

When storing glTF data in source control, it's often convenient to store its buffers as separate files (e.g., `.bin` for vertex data, `.png` for textures, etc).  This makes it easier to change some small pieces (e.g., small JSON details, or the image size of a texture) without re-saving the whole file and fighting merge conflicts.

Similarly, adding more texture LOD images next to the original texture image(s) is easier when textures stored as separate files.

Casually browsing the image assets is also easier with separate files (just open up the `*.png` file directly).

Currently, all of our buffer(s) are `data://` URIs inside the JSON, which ends up being awkward to manipulate (and presumably slower to load), in all of the above cases.

**Describe the solution you'd like**

Across all of our glTF-relevant geometry endpoints, ensure that they can load non-embedded `*.gltf` files, i.e., where the glTF buffers and images are not `data://` URIs but rather relative pathnames.

- [x] Meshcat (done in #20877).
- [x] RenderEngineGltfClient (done in #20933).
- [x] RenderEngineVtk (pending in #21002).
- [ ] https://github.com/RobotLocomotion/drake-ros/issues/335
- [x] Provide a fully-worked sample for users to copycat
   - [x] #21039
   - [x] #21052

**Describe alternatives you've considered**

There's not really any good alternative.  It's easy to use something like https://gltf-transform.dev/ to extract the buffers for inspection / editing and then re-pack it again, but that's cumbersome and doesn't solve merge conflicts.

**Additional context**

Using individual files for each geometry buffer of texture image will probably also be critical for #19598.

**Comment by jwnimmer-tri** [comment]
Using `model_visualizer --show_rgbd_sensor`, I've confirmed that a gltf with external assets already loads up correctly.  I think the only remaining task on that front is to lock that in with a regression test (assuming we don't already have one).

**Comment by jwnimmer-tri** [comment]
Perhaps a good "acceptance test" would be to convert `tri_homecart` to use glTF with external resources.

**Comment by jwnimmer-tri** [comment]
I _think_ I have all of the PRs open to fully solve this issue, including documentation.

If anyone can think of anything I've missed, let me know.
