### ISSUE TITLE
[geometry]  Tracking for CompliantCompliant intersection benchmark and algorithm changes.

### ISSUE THREAD

**Issue by joemasterjohn** [RobotLocomotion/drake#21744]
This issue serves to capture baseline data for `//geometry/benchmarking:compliant_mesh_intersection_benchmark` as well as track the progress of the PR train for a new contact surface algorithm.

The proposed list of PRs are as follows. They all involve changes cherry-picked from [my WIP branch](https://github.com/joemasterjohn/drake/tree/hydro_contact_surface_improvements).
- [ ] Introduce compliant/compliant intersection benchmark #21742
- [ ] Add pressure range culling to existing compliant intersection code.
- [ ] Add VolumeMeshTopology data structure.
- [ ] Create mesh topology, surface mesh and mapping for compliant geometries.
- [ ] Add new compliant geometry intersection algorithm.
- [ ] Update benchmark baselines.

cc: @amcastro-tri @DamrongGuoy @SeanCurtis-TRI

**Comment by joemasterjohn** [comment]
Baseline at 3c17fc15e5a296b40035d9684b6372f8ee330607

```
Run on (64 X 3566.43 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x32)
  L1 Instruction 32 KiB (x32)
  L2 Unified 1024 KiB (x32)
  L3 Unified 22528 KiB (x2)
Load Average: 2.31, 1.43, 2.44
---------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                                                                         Time             CPU    Allocs   Iterations
---------------------------------------------------------------------------------------------------------------------------------------------
CompliantMeshIntersectionBenchmark/SoftSoftMesh/0/0/min_time:0.020/min_warmup_time:0.010      0.125 us        0.125 us   140.438       228197
CompliantMeshIntersectionBenchmark/SoftSoftMesh/0/1/min_time:0.020/min_warmup_time:0.010       10.1 us         10.1 us   160.438         2687
CompliantMeshIntersectionBenchmark/SoftSoftMesh/0/2/min_time:0.020/min_warmup_time:0.010       46.4 us         46.4 us   297.438          594
CompliantMeshIntersectionBenchmark/SoftSoftMesh/0/3/min_time:0.020/min_warmup_time:0.010        625 us          625 us      2.7k           44
CompliantMeshIntersectionBenchmark/SoftSoftMesh/1/0/min_time:0.020/min_warmup_time:0.010      0.116 us        0.116 us   657.188       237007
CompliantMeshIntersectionBenchmark/SoftSoftMesh/1/1/min_time:0.020/min_warmup_time:0.010       10.4 us         10.4 us   679.188         2667
CompliantMeshIntersectionBenchmark/SoftSoftMesh/1/2/min_time:0.020/min_warmup_time:0.010       96.9 us         96.9 us      1.0k          292
CompliantMeshIntersectionBenchmark/SoftSoftMesh/1/3/min_time:0.020/min_warmup_time:0.010       2500 us         2500 us     11.2k           11
CompliantMeshIntersectionBenchmark/SoftSoftMesh/2/0/min_time:0.020/min_warmup_time:0.010      0.117 us        0.117 us      1.2k       233711
CompliantMeshIntersectionBenchmark/SoftSoftMesh/2/1/min_time:0.020/min_warmup_time:0.010       11.9 us         11.9 us      1.2k         2356
CompliantMeshIntersectionBenchmark/SoftSoftMesh/2/2/min_time:0.020/min_warmup_time:0.010        198 us          198 us      1.9k          135
CompliantMeshIntersectionBenchmark/SoftSoftMesh/2/3/min_time:0.020/min_warmup_time:0.010       7181 us         7181 us     36.1k            4
CompliantMeshIntersectionBenchmark/SoftSoftMesh/3/0/min_time:0.020/min_warmup_time:0.010      0.117 us        0.117 us     10.1k       242614
CompliantMeshIntersectionBenchmark/SoftSoftMesh/3/1/min_time:0.020/min_warmup_time:0.010       27.8 us         27.8 us     10.2k         1016
CompliantMeshIntersectionBenchmark/SoftSoftMesh/3/2/min_time:0.020/min_warmup_time:0.010        841 us          841 us     12.7k           34
CompliantMeshIntersectionBenchmark/SoftSoftMesh/3/3/min_time:0.020/min_warmup_time:0.010      59971 us        59969 us    433.0k            1
CompliantMeshIntersectionBenchmark/SoftSoftMesh/4/0/min_time:0.020/min_warmup_time:0.010      0.120 us        0.120 us     83.4k       226392
CompliantMeshIntersectionBenchmark/SoftSoftMesh/4/1/min_time:0.020/min_warmup_time:0.010       19.8 us         19.8 us     83.4k         1311
CompliantMeshIntersectionBenchmark/SoftSoftMesh/4/2/min_time:0.020/min_warmup_time:0.010       3736 us         3735 us    203.2k            7
CompliantMeshIntersectionBenchmark/SoftSoftMesh/4/3/min_time:0.020/min_warmup_time:0.010     483407 us       483390 us      3.5M            1
```
