### ISSUE TITLE
Cleaning the RigidBodyTree API

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#2213]
I am collecting here the **TODO(amcastro-tri)**'s that I pushed with PR #2207. These intend to identify some API and related issues we have in Drake right now within `RigidBodyTree` and related classes:

rigid_body_tree_test.cc. These have to do with the actual user API:
- [ ] rigid_body_tree_test.cc (40, 82, 119, 127, 147): Replace `RigidBody*` user instances with a more lifetime controlled smart pointer like a drake::unique_ptr_reference (internal communication with @sherm1). Or otherwise migrate to PIMPL implementation as suggested in #1854.

KinematicsCache.h:
- [ ] `KinematicsCache::getNumPositions`: Right now this method computes the total number of positions and is called within the constructor on initialization of the KinematicsCache. This method should be moved to something like (notice Google style guide naming) `KinematicsCache::ComputeTotalNumberOfPositions()` which would be called on initialization (costly method). A second method `KinematicsCache::total_number_of_positions()` would return the previously computed number of positions during initialization. 
- [ ] `KinematicsCache::getNumVelocities`: see previous check box for `getNumPositions`.

RigidBody.h:
- [ ] Member `RigidBody::parent` (a RigidBody*): it should be private and changed to `parent_`. 
- [ ] Create an accessor: `RigidBody& parent() const` and the corresponding mutable version.  
- [ ] Move `RigidBody::CollisionElement` to a better place. Now it is nested within `RigidBody`.
- [ ] `CollisionElement` constructor. The constructor gets passed a reference to the body the collision element belongs to. Here there are two issues: 1) this reference should be `const` if only used to reference the body. 2) should the collision element hold a reference (actually a pointer right now) to the actual rigid body at all?

RigidBody.cpp:
- [ ] `RigidBody* RigidBody::CollisionElement::getBody()`: Now it returns a pointer to `RigidBody`. Should it return a reference? is there a reason why now it is returning a pointer. In other words, is the nullptr semantics purposely used?. 
- [ ] `RigidBody* RigidBody::CollisionElement::getBody()`: As per Googly style guide: getBody() -> get_body().
- [ ] `const RigidBody* RigidBody::CollisionElement::getBody() const`. Same as discussed above.

RigidBodyFrame.h:
- [ ] as with `CollisionElement`, `RigidBodyFrame` holds a pointer to the `RigidBody` it belongs to. The constructor right now takes a pointer. Though in this case `compareRigidBodySystems.cpp` calls for nullptr semantics. Is this necessary? is it correct to have a pointer to the `RigidBody` in `RigidBodyFrame` at all?

RigidBodyTree.h:
- [ ] `RigidBody* RigidBodyTree::findJoint(std::string, int)`: the name is misleading. It seems like you ask for a joint and you get a `RigidBody`? 
- [ ] member `RigidBodyTree::bodies`. It should be private. Rename to `bodies_`. Start accessor `RigidBodyTree::body(int)` implemented in #2207.
- [ ] `RigidBodyTree::SortTree()` implemented in #2207 from original code in Drake (#2207 only changed it to use `std::unique_ptr`'s but the logic remains intact). This method is quite inefficient resourcing to `std::vector` `RigidBodyTree::bodies` being resized during the sorting. A better strategy could be to create an `std::vector` (or `Eigen::Vector`) of `int`s for each body in the tree (and therefore the vector is size `bodies.size()`) holding the depth within the tree (simple to compute by navigating up the tree stack following the `RigidBody::parent` pointer. Then `std::sort` (or any other fast sort, maybe a drake::math::quick_sort?) this array (fast). Then use the permutation to reorder original `sted::vector` of `std::uniqe_ptr`'s.

RigidBodyTree.cpp:
- [ ] `RigidBodyTree& RigidBodyTree::add_rigid_body(std::unique_ptr<RigidBody> body)`: This method does more than a simple `push_back` to an STL container. It computes the **index** of the object. I'll quote myself from my **TODO** in #2207: 

> body indexes should not be initialized here but on an initialize call after all bodies and RigidBodySystem's are defined. This initialize call will make sure that all global and local indexes are properly computed taking into account a RigidBodySystem could be part of a larger RigidBodySystem (a system within a tree of systems).
