### ISSUE TITLE
MEX compilation without mex.cmake tracker

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#3617]
General:
- [x] #3681
- [x] #3596
- [x] #3586
- [x] #3186

IRIS:
- [x] #3620 
- [x] rdeits/iris-distro#49
- [x] rdeits/iris-distro#48
- [x] rdeits/iris-distro#47

SNOPT:
- [x] #3645
- [x] RobotLocomotion/snopt#9
- [x] RobotLocomotion/snopt#10

Swigmake:
- [x] #3654
- [x] #3637
- [x] #3632 
- [x] rdeits/swigmake#4
- [x] rdeits/swigmake#3
- [x] rdeits/swigmake#2

**Comment by david-german-tri** [comment]
:confetti_ball:
