### ISSUE TITLE
[META] Purge all System 1.0 code

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#3960]
Tracking issue for all of the subtasks.  Edit this OP with the checklist:
 - [x] `examples/Acrobot` filed as part of #3975.
 - [x] `examples/Pendulum` filed as part of #3975.
 - [x] `examples/Quadrotor` filed as part of #3975.
 - [x] `examples/Atlas` filed as #3976.
 - [x] `examples/kuka_iiwa_arm` filed as #3977.
 - [x] `automotive` demos filed as #3978.
 - [x] `ros` demos filed as #3979.
 - [ ] `rigid_body_plant_system1_test` filed as #4305.

Do not discuss specific tasks in this issue; discuss only in the sub-issues.

**Comment by jwnimmer-tri** [comment]
The only remaining issue is 4305, so I'll close the meta-issue.
