### ISSUE TITLE
Template RigidBodyTree on <T>

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#3987]
First check-box in #3908.
This work will be performed in several stages:

- [x] Dummy parametrization of `RBT` on `<T>`. PR #3940 merged.
- [x] Template `RigidBody` on `<T>`. PR #4124 merged.
- [x] Template `RigidBodyFrame` on `<T>`. PR #4406 merged.
- [x] Template `RigidBodyLoop` on `<T>`. PR #4418 merged.
- [x] Explicit instantiation on other types than `<double>`. PR #4419 merged for instantiation on `AutoDiffXd`.
- [ ] Template `DrakeJoint` on `<T>`.
- [ ] Implement `RBT::ToAutoDiffXd()`. This might be the solution to some of the "pain points" highlighted above. Also needed to update `rigid_body_tree_inverse_dynamics_test.cc`. See #4044.
- [ ] Replace template parameter `<Scalar>` in RBT's methods by `<T>`, make use of `Eigen::Ref` where applicable, get rid of per-method explicit instantiations.
NOTE: Some pain points will be found when:
  - updating `contactConstraintsmex.cpp` [at this point](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/test/benchmarkRigidBodyTree.cpp#L75) to use `RigidBodyTree<AutoDiffScalar<...>>`. [See comment here](https://reviewable.io/reviews/robotlocomotion/drake/3940#-KVWtPogPpSakEcE5hto).
  - When updating `benchmarkRigidBodyTree.cpp` to convert (`cast<Scalar>`?) `RBT<double>` to `RBT<AutoDiffScalar>`. See [comment here](https://reviewable.io/reviews/robotlocomotion/drake/3940#-KVX13lBNh7tShNgrVjn). Probably this is the very first place where to test these ideas.
  - Revisit also inverse dynamics test regarding a `cast<Scalar>` method. [Particularly here](https://github.com/RobotLocomotion/drake/blob/master/drake/systems/plants/test/rigid_body_tree/rigid_body_tree_inverse_dynamics_test.cc#L118).
- [ ] Check that the warnings in #4169 are gone.
