### ISSUE TITLE
Implement caching in System 2

### ISSUE THREAD

**Issue by sherm1** [RobotLocomotion/drake#4364]
The preliminaries of the caching system are present in System 2 but the internals are not yet functional. Per discussion with David and Russ (see #4127) I will implement the all-pull architecture. I will attempt to do this in a series of smallish narrowly-focused PRs. Here is some background and an initial implementation plan. A more extensive design document is [here](https://docs.google.com/a/trinst.com/document/d/1AmOTdugb2TF_heTwxy4iK0CZ4jbZdgRrTbkKJ_bqAmM/edit?usp=sharing). The WIP branch containing the full implementation is #7668.

### Basic architecture
- Cache entries of arbitrary type are allocated to hold the results of all significant computations, including built-ins like derivatives, updates, and output ports as well as user-defined internal computations. Prerequisites for these computations are explicitly noted during allocation.
- Computation is initiated when a result is requested via an “Eval” method, if the result is not already up to date with respect to its prerequisites.
- Cached results are invalidated when any of their prerequisites change.

### Value sources
When a cache entry is allocated, a list of prerequisite value sources is provided. There are five kinds of value source within a System’s Context that can serve as prerequisites for cached results within that Context:
1. Time
2. Input ports
3. Parameters
4. State (including continuous, discrete, and abstract subgroups)
5. Other cache entries

Each value source (include subgroups of state) has a unique DependencyTicket that is used to designate that source as a prerequisite for a cache entry. Tickets are assigned when Context resources are allocated. Each value source maintains a list of its dependents (called "subscribers") so that it can perform invalidation. Cache entries will typically serve as both sources (prerequisites) and subscribers.

### Output ports
An Output Port for a System is a “window” onto one of the value sources within that System's Context; that is the only way in which internal values of a System are exported to other Systems in a Diagram. That value source may be a cache entry allocated specifically for the Output Port, or may be a pre-existing source like a state subgroup or a cached value that has other uses. An Output Port is a subscriber of its source, and a prerequisite to the downstream Input Ports that it drives.

### Input ports
The value source for a subsystem Input Port is either 
- an OutputPort of a peer subsystem, or
- an InputPort of its parent Diagram, or
- a locally-stored value (a "fixed" input port).

### Implementation plan (details likely to change)
- [x] (issue #2890) Replace EvalOutputs with EvalOutputPort(i) to allow individual triggering of output computations (consider output_port.Eval() to avoid case statement).
- [x] Move the value source for Output Ports into the Context for uniform caching treatment.
- [x] Automatically allocate cache entries for known computations such as derivatives, updates, and outputs.
- [x] (issues #2738, #3155, #3482) Ensure that all Eval methods return a reference and are non-virtual, uniformly invoking user-written Calc overrides that perform computations into an output argument. This is mostly renaming existing methods, and adding boilerplate wrappers [like this](https://github.com/RobotLocomotion/drake/issues/3155#issuecomment-240258256).
- [x] Implement DependencyTracker abstraction for use in registration and invalidation (some of this is already implemented).
- [x] Ensure that caching can be disabled for testing and debugging; that will also be useful for debugging of dependency graphs in release code.
- [x] Implement straightforward but possibly slow invalidation scheme (“option 1”) from #4127 [comment](https://github.com/RobotLocomotion/drake/issues/4127#issuecomment-261346082).
- [ ] Ensure API allows pointing an Output Port at any internal value source (no user-written method required in that case and avoids copying). 
- [x] Add instrumentation (counters) useful for debugging, verifying proper operation in regressions, and performance investigation. Provide sufficient introspection to allow reconstruction of prerequisite DAG for listeners and dependents DAG for sources.
- [ ] Determine direct feedthrough matrix automatically from dependency graph.
- [ ] Add runtime loop-detection tickets to cache entries (used during computation of prerequisites). 
- [x] Provide unit tests that verify identical results with caching enabled or disabled and show that fewer computations occur when enabled.
- [x] Provide unit tests verifying that invalidation propagates correctly for all supported value sources.
- [x] Implement faster invalidation scheme (“option 2”) from #4127 [comment](https://github.com/RobotLocomotion/drake/issues/4127#issuecomment-261346082).
- [ ] Measure performance and audit for unnecessary copying and computation.
