### ISSUE TITLE
MultibodyTree features requests.

### ISSUE THREAD

**Issue by amcastro-tri** [RobotLocomotion/drake#5013]
This issue is opened to track a number of issues, feature requests, ideas for RBT that need to be taken into consideration in the design of `MultibodyTree`. This issue will therefore help close those old `RBT` issues without loosing track of them.
The need for `MultibodyTree` was identified in #4633.

These items are listed in the order I think they will get resolved:

- [x] Small lightweight spatial algebra library. #2752
- [x] Full templatization on `<T>` with transmogrification capabilities. #3987
- [x] Design a class hierarchy that encompasses the concept of `Frame`'s. #4407
- [x] Simplify API for programmatic construction and queries. #4328
- [x] Provide a solid representation of unique identifiers when needed. #4291
- [x] Compute Rigid Body Inertias with respect to `Bo` rather than `Wo`. #4621.
- [ ] Provide mechanism for state validation. #4838
- [ ] On `MultibodyPlant<T>`: Provide clean API access to cached computations. #3325
- [x] Provide a capability to represent several model instances. #5190, relates also to #3088
- [x] Provide documentation on spatial inertia methods and mass matrix computation. See old PR #4591 for RBT.
- [x] Move/adapt documentation provided in old PR #4311.
- [ ] Transparent (and safe) API for joints internally implemented with Mobilizer's or Constraint's. #3673
- [x] Remove `drake::SpatialForce` typdef in conflict with new class `drake::multibody::SpatialForce`. #6731
- [ ] Torsional springs and distance constraints between two points, per [comment](https://github.com/RobotLocomotion/drake/issues/7025#issuecomment-336220447).  Partially addressed by #10658.

For a full list of issues on `RBT` you can see #3908

**Comment by kunimatsu-tri** [comment]
I have a request for MultibodyTree, which is related to #3088.

I'm working on "label image" output feature of RGBD camera simulator.
The "label image" contains an unique ids associated to an object in each pixel .

From rendering point of view, both the terrain and the sky should have unique ids, but the current RBT doesn't handle them. The temporal solution is assigning arbitrary ids to the sky and the terrain.
This is OK for now, but I feel the sky and the terrain are something special and they should have always the same ids if possible.

So, I want to request that we assign unique ids for the sky (or space or world if it's appropriate) and the terrain as follows:
```
sky: 0
terrain: 1
```

**Comment by sherm1** [comment]
#3088 is referring to physical bodies (in particular world), which are not geometry. RBTree currently knows about collision geometry, but not visual geometry. We are splitting out all geometry handling (both physical and collision) to GeometryWorld so your request might be for that? MultibodyTree will not have any geometry at all.

@SeanCurtis-TRI may have a useful comment since he is working on GeometryWorld.

**Comment by kunimatsu-tri** [comment]
Thanks. Resolved by discussion on Slack. I withdraw the request.

For the record, we've got a consensus that we should **NOT** define terrain to have an unique id since terrain could have more specific semantics than just terrain, and that it's OK for the sky (space, world, empty or whatever) to have ID zero in GeometryWorld.

**Comment by TristanThrush** [comment]
Would it be good to add support for the <static> tag (from the SDF format), so that the Drake SDF parser can handle an SDF for multiple objects and make some of them floating and some of them fixed?

**Comment by EricCousineau-TRI** [comment]
Related: Other feature requests are in #7025 as well

\cc @avalenzu

**Comment by sammy-tri** [comment]
Marking the model instance bits done based on #8986 and #9041

**Comment by sherm1** [comment]
cc @tri-ltyyu

**Comment by EricCousineau-TRI** [comment]
This done?

**Comment by sherm1** [comment]
I think this is far enough along that we could close it and have separate issues if there is anything left to be done. What do you think @amcastro-tri ?

**Comment by amcastro-tri** [comment]
agree.
