### ISSUE TITLE
GeometrySystem PR strategy

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [RobotLocomotion/drake#6578]
`GeometryWorld`/`GeometrySystem` is big enough that it has to be decomposed into smaller PRs to introduce into Drake.

The basic strategy is to do a top-down approach. THe goal is to validate the public API first and then gradually introduce the details that support it. This will involve stubbed implementations and limited testing that gradually get filled out with subsequent PRs. This plan tries to balance doing things in parallel (so that independent components can get through the PR process without hanging on each other) against making sure that there's a systematic progression. Indentation below indicates partial dependency.

- [X] Initial GeometrySystem (introduces registration API). (#6579)
  - [X] GeometrySystem input/output API introduced (#6606)
  - [X] Introduce supporting data structures (not an actual PR)
    - [X] Add GeometryState
      - [X] Topology support
        - [X] Initial State and support for Frames (#6688)
          - [X] Support for geometry instances. (#6774)
            - [X] Unit tests. (#6813)
            - [X] Introduce shape specification (#6814)
            - [X] Extend shapes to include cyilnder (#7163)
            - [X] Anchored geometry (#6854)
      - [X] Pose computation/evaluation
          - [X] Pose data (#6873)
          - [X]  Pose value transport -- getting kinematics values *into* geometry world (#6888)
        - [X]  Add visualization of GeometrySystem's state (includes `GeometryContext`, additional data in `GeometryState` and `GeometrySystem`). (#6953)
    - [ ] Add GeometryEngine (stub implementation)
- [ ] Introduce `examples/geometry_world/bouncing_ball` demo which will serve as the basis for putting `GeometrySystem` to work. (#6582)
  - [X] Add a simple "solar system" to exercise `GeometrySystem` data flow and visualization. (#7061)
  - [ ] Enable contact in `drake/examples/geometry_world/bouncing_ball`.
  - [ ] Add multi-ball example on finished `GeometrySystem`.
- [ ] Add GeometryWorld (maybe). GeometryWorld may be an unnecessary piece of fluff. I'll investigate if `GeometrySystem` can be just as meaningfully exercised floating alone as `GeometryWorld` would have done.

* This will be updated as we go.

**Comment by SeanCurtis-TRI** [comment]
This has grown stale; the work as documented above is complete and life has moved on.
