### ISSUE TITLE
[geometry] SceneGraph requests

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#8473]
Not trying to rush... just capturing these for tracking.  I believe this was the primary outcome from the Monday discussion:

- [X] frame id input port should disappear.  frame id should be combined with pose (and velocity, acceleration) input ports. (#8492)
- [X] add support for diffuse color material properties to GeometryInstance (and send to DrakeVisaulizer). (#8474)
- [ ] Support visualization blocks as a consumer of `SceneGraph`
   1) class method that could be called, e.g. from the visualization class constructor, that returns a list of frame id's and geometry instances. 
   2) query method that returns list of frame id's and poses.
   3) Edit 5/14/20: Currently in flight; the hypothesis is that `QueryObject` and `SceneGraphInspector` have sufficient API to instantiate a visualizer by introspecting. Will close this when we have a finished `DrakeVisualizer` system.
- [X] (Related to visualization) Reduce the current boilerplate required to connect a `SceneGraph` to `drake_visualizer`. Draft solution can be found in #8526. It will be closed and generic visualization + boilerplate reduction will be rolled into a single architecture (albeit two PRs).
- [X] refactor "GeometrySystem" => "SceneGraph" (#8639)
- [ ] Parameterized geometry. If an upstream, geometry source system has parameters, those parameters may affect the geometries registered with `SceneGraph`. For example, the rimless wheel may have a parameter-dependent number of spokes, or the acrobot may have a parameter dependent arm length. These two examples are (and should be separable) because they reflect a significant difference in implementation challenges.
    - Changing the properties of registered geometries (specifically the size of geometries)
    - Changing the number of geometries. This is particularly interesting because parameters can be changed during simulation. I.e., a simulation can be run from time 0 to 10 with a fixed parameter value, then code can arbitrarily change the parameter value to move forward in time. At that point, the abstract state of scene graph would have to change the *number* of geometries for moving forward.
- [x] Support for SymbolicExpression.  (Otherwise it becomes considerably more awkward for systems that do support SymbolicExpression to have methods that register geometry, etc, with SceneGraph).

**Comment by SeanCurtis-TRI** [comment]
@RussTedrake I'm starting on this shopping list. Did you have a proposal for your "visualization" blocks?

The issues as I see it is:
1. What info is actually communicated and how is it organized into structs?
2. As your proposal alludes, there are two operations "declaration" and "update". Probably a unique struct for each.
3. What is the calling mechanism? Both through a QueryObject? Declaration through a `SceneGraph` system method? 

Also, did we want to add the visualization utility system which combines a `SceneGraph` and a the LCM-publishing mechanism compatible with `drake-visualizer` to the shopping list?

**Comment by sherm1** [comment]
There was also the issue of needing to register geometry prior to being able to obtain its dimensions from parameters in the Context. I believe @RussTedrake said he had to create the System twice in order to get a usable Context, look at its parameters, and then create a new System using them.

**Comment by RussTedrake** [comment]
@sherm1 -- i didn't include that on this short list, because it might be a bigger topic.  I think, longer term, we might need to support runtime registering of geometry.  But i think the current state of affairs is what you would expect given the systems framework.

@SeanCurtis-TRI -- while i'm certainly open to ideas, I chose the words on my wishlist carefully.  i think a class method for getting the initial geometry (e.g. as a list of frame_id, geometryinstance pairs via a struct) and a query via the output port for the poses (again via a std::list?).  Any variations of this are aok for me?

Adding the diagram sugar of SceneGraph+Visualizer sounds great to me, too.

**Comment by SeanCurtis-TRI** [comment]
1. Post-allocation geometry registration -- I formerly had an API that allowed exactly this. The difference is it required passing in a context. There's also a subtlety about what it means to allocate a default context. Right now, the default context includes everything registered before initial allocation. So, if I "alloc" context over and over, I'll always get the same scene graph. Would that default allocation change based on subsequent graph changes? Or, would it be better to move *all* registration to post context allocation and the default allocation is *always* empty? We'll have to revisit the design decisions from before.

2. I realize now that I hadn't interpreted your comment the way you'd intended. I didn't read "geometry instance" as `GeometryInstance` and therefore interpreted your original request as a concept and not an implementation. Certainly, it would be possible to do that literally -- a mapping of frame ids to sets of `GeometryInstance`s.  :)

3. I'd still advocate reporting (frame id, pose) pairs as an output port instead of a query. On the one hand, it *is*, strictly speaking, a query and making it part of a query object seems reasonable from that perspective. But, on the other hand:
      - For me, queries are about *operations* on the input poses and, for this particular "query", the operation is just a mux; so simple it's almost *not* an operation.
      - This also hints at the possibility, in the future, of decomposing the single query object into multiple query objects so that we can refine the dependencies at a more granular level. Looking at a diagram, it would be more clear just what kind of dependency lies between a SceneGraph and a consumer system.

**Comment by RussTedrake** [comment]
Sounds great to me.

**Comment by RussTedrake** [comment]
#16526 will resolve one more of these (SceneGraph support for Expression).

**Comment by jwnimmer-tri** [comment]
It's not clear to me what work (if any) remains here.

We already have API to interrogate the scene graph (query object, geometry inspector), to change shapes, and to add geometries.

What's still missing?  This issue doesn't seem actionable, currently.

Perhaps opening a more specific issue for each remaining missing item (and closing this issue) would help clarify.

**Comment by RussTedrake** [comment]
I agree.  The ideas here are stale at best.
