### ISSUE TITLE
Trajectory- and waypoint-following agents

### ISSUE THREAD

**Issue by jadecastro** [RobotLocomotion/drake#8529]
We currently have some support for following waypoints but no way of specifying trajectories and representations for agents in general (systems other than cars).  This is a step toward making stochastic agents for verification/falsification.  This is just to track some TODOs toward this.

1. Agent models
- [x] For `TrajectoryCar`, create a struct (`AgentData`) containing details of the agent. As a minimal instantiation, we'd populate this with an `AgentType` enum (`AgentType::{Car | Bicycle | etc..}`) but this could contain meta-information like bounding boxes, parameters, etc.  These could internally change the underlying behavior of `FooAgent` and what parameters it uses. #8725

2. Support for trajectories
- [x] Create an agent that follows a trajectory (e.g. `Trajectory` or `PiecewisePolynomial`), rather than a set of waypoints. This would be somewhat similar to what `TrajectorySource` does in addition to having the outputs of the existing `TrajectoryCar`. #8597, #8725

3. Waypoint following
- [x] Extend support of `TrajectoryAgent` to encompass waypoints having speeds (others too?) and interpolating between waypoints via additional ctors in `AgentTrajectory`.  #8720
- [x] ~Rename `TrajectoryCar` to `PathFollowingAgent`, adding the `AgentData` struct as a constructor argument.~ (keeping TrajectoryCar as-is)

@stonier

**Comment by jadecastro** [comment]
Closing, as all tasks for this issue are complete.
