### ISSUE TITLE
MultibodyTree + pydrake: Binding feature requests

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9311]
Suggested order of operations:

- [x] Load an SDF and query basic topology from `MultibodyPlant` (#9281)
  - [x] Weld joints (#9345)
- [x] Simulate + Visualize a `MultibodyPlant` (#9322)
- [x] `RigidTransform` (#9318)
- [x] Compute kinematics for `MultibodyTree` / `MultibodyPlant`
  - [x] Simple transforms + geometric Jacobian (#9346)
- [x] State vector indexing from #9388 and #9383
- [x] Spatial Velocities
- [x] Compute dynamics for `MultibodyTree` / `MultibodyPlant`
- [x] Multibody IK - @hongkai-dai 
- [x] All types of bodies, mobilizers. joints, joint actuators, and force elements
- [x] Construct a `MultibodyPlant` / `MultibodyTree` programmatically

\cc @amcastro-tri

**Comment by pangtao22** [comment]
In Pset1 of 6.881 (to be released on Sep 11), we are using the following RBT functions to control the robot and in testing:
```
rbt.B
rbt.doKinematics
rbt.CalcBodyPoseInWorldFrame
rbt.inverseDynamics
```

Not used in pset1 but could be used for future psets:
```
rbt.relativeTwist
rbt.geometricJacobian
rbt.geometricJacobianDotTimesV
```

Thanks!

**Comment by EricCousineau-TRI** [comment]
Per f2f with @amcastro-tri, for the actuation matrix / projection matrix `B`, we may need some sugar methods to obtain the projection matrices.
@hongkai-dai Can I ask if you'll be submitting a PR for getting things such as the state and Jacobians in a specified order? If so, I can then build on top of that PR to get `B`.

**Comment by hongkai-dai** [comment]
@EricCousineau-TRI I do not think I will send a PR on getting things like state and Jacobians. By discussing with @amcastro-tri , I will PR a method to get the bounds on the generalized positions.

**Comment by tri-ltyyu** [comment]
Check with @EricCousineau-TRI on status

**Comment by EricCousineau-TRI** [comment]
Updated checkboxes; we can consider shifting the remaining bits that are not immediately necessary to separate issues.

**Comment by EricCousineau-TRI** [comment]
AFAIK, with contributions from @gizatt, @mpetersen94, and other Drake authors, we've generally covered this list. Closing for now.
