### ISSUE TITLE
Move rigid_body_tree and related into subfolder

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake#9343]
As a first step of #9314, we should move rigid_body_tree related code (joints, shapes, etc.) in a subfolder.

The goal is to keep the CMake-installed paths unchanged, and to `alias()` the Bazel build labels, so that this will not disturb downstream users.

However, users with Drake forks with changes to RBT itself will have to be merge up.  However, since the code is unchanged, hopefully that is easy.

Proposed PR train:
- [x] #9360 Move the `parsers/` files.
  - Add shims to keep as minimal as possible.  No changes for any Drake users, _except_ those who have Drake forked and have local changes to the moved code.
- [x] #9355 Move the rest of the RBT-related files.
  - Add shims to keep as minimal as possible.  No changes for any Drake users, _except_ those who have Drake forked and have local changes to the moved code.
- [x] #9444 Update all of Drake's BUILD files to use the new attic packages for their `deps`.
- [x] #9444 Deprecate the legacy Bazel packages e.g.  `//multibody/parsers` for Bazel downstreams.
- [ ] Do something about `multibody/rigid_body_plant/visualization` (see #9452).
  - Wait until #9653 has landed.
- [x] There are some uses in Drake of stuff from the attic, where the using-code is *not* soon to be deprecated.  We should audit Drake's use of attic code, and move things _out_ of the attic as appropriate.
  - [x] #9457 For example, some test models, or the SDF "package map" utilities.
    - [x] #9784 `parsing::ResolveFilename` unit tests might actually only live in the attic right now.
  - My (jwnimmer-tri) audit didn't find anything else.
- [x] #9799 Remove the deprecated / empty Bazel pacakges later (breaking change).

**Comment by jwnimmer-tri** [comment]
WIP at https://github.com/jwnimmer-tri/drake/tree/multibody-legacy/multibody

**Comment by jwnimmer-tri** [comment]
Due to bazelbuild/bazel#5802, the easy way to warn Bazel downstreams about the new package names will not work.  I'll see if I can find another mechanism.

**Comment by jwnimmer-tri** [comment]
The only unfixed item from the checklist above is that the `multibody/rigid_body_plant/visualization` stubs are still intact, even though the logic has moved elsewhere.

We should probably add deprecation warnings to them, that users should stop listing them explicitly, and then later remove them.  We can do that anytime we feel they are in the way, no need to keep this issue open for it.

Declaring victory.
