### ISSUE TITLE
pydrake doc: Fixes for Python documentation generation via Sphinx

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#9599]
Follow-up from #9578:

- [x] 1. (Eric) Do not require that `pydrake` be built in two separate configurations when the host is the same as the target (esp. on Ubuntu Xenial). 
    * Could use `--distinct_host_configurations=false`.
    * If we make this a `runfiles` rule, then we can use the `refresh` script to auto-generate everything, and do not need to commit these files to source control.
- [x] 2. The current `TemplateClass` setup hides the documentation for actual classes, like `pydrake.systems.framework.System_[float]`; need to figure out how the documentation will come from that. #9634
   * Hopefully there is a way to make a plugin in Sphinx to change how `autodoc` gets its items to document; this way, we could parse `TemplateClass` instances.
- [x] 3. The side bar uses the whole module name, rather than nesting submodules in a list. Is there an option for this?
- [x] 4. We should show bases, but exclude `pybind11_builtins.pybind11_object`. #9634
- [x] 5. (Eric) Bindings which have symbols comes from `_{module}_py` have their docstrings reflect this (e.g. `abs(self: pydrake._autodiffutils_py.AutoDiffXd) → pydrake._autodiffutils_py.AutoDiffXd`); we can either fix this at the binding level, or see if we can tell Sphinx to treat that differently. (#9756)
- [ ] 6. All sphinx warnings should be repaired, and then the rule should use `-W -q` (to promote them to errors) instead of `-Q` (silencing all warnings).
- [x] 7. (Jamie) Typedef / using aliases do not have docstrings. (#9703)
- [x] 8. (Jeremy) Reflect deprecation in Python documentation (manually or automatically).  (#11131)
- [ ] 9. (Eric) See if types can be abbreviated; see if a reference can be backed out of type annotations instead. At present, it looks like a mess:
    > ![image](https://user-images.githubusercontent.com/26719449/46701395-91e21280-cbed-11e8-9cea-5cbdb8fcdeaf.png)
- [x] 10. (Jamie) Ensure that constructors show up in a clear and easy-to-visually-parse fashion. (#9652)
- [x] 11. (?) Add simple regression test on current Sphinx infrastructure.
- [x] 12. (Jamie) Make `mkdoc.py` Napolean-friendly (e.g. lists)
   - [x] Doxygen fixes for reST friendliness (lists) (#9643)
   - [x] Markdown translation (#9703, #9805)
   - [x] Styleguide (tracked by #9745)
- [x] 13. (Eric) Factor out common functionality between `pydrake/doc` and `doc`
- [x] 14. ~(Eric) Use a pegged version of Sphinx (#9654)~ (punting)
- [x] 15. (Eric) Documentation on documentation, i.e. #9657
- [x] 16. ~(Eric) Less fragile overload documentation (may move this to separate issue)~ Resolved by #10031
- [x] 17. (Jamie) Add unittest on Sphinx -> Markdown, decouple it from general `mkdoc.py` regression test
- [ ] 18. (Eric) Fix docs for `MultibodyTreeElement` mixin (forward decls cutting off members?)
- [x] 19. (Eric) Render Systems diagrams in Sphinx.
    * This could be done either via `mkdoc` subs, or via our Sphinx plugins. Just doing it with the Sphinx plugin sounds the cleanest, so that people can still see the original stuff in Jupyter and what not.

\cc @jwnimmer-tri @jamiesnape

**Comment by jamiesnape** [comment]
> The side bar uses the whole module name, rather than nesting submodules in a list. Is there an option for this?

It uses the text from the toctree, i.e., the page title, by default. There is not an option, but you can override the text. Personally, I like how it looks at present, though.

**Comment by EricCousineau-TRI** [comment]
Yeah, the current template makes this look much better. Will close that item.

**Comment by EricCousineau-TRI** [comment]
Sigh... Seems that supporting Sphinx >= 1.5 on Xenial is a bit of an uphill battle, since it includes Python packages that are not installed as part of the system.

Will slot that along with Jupyter stuff w.r.t. PyPI archives (or conditional support?....).

**Comment by jwnimmer-tri** [comment]
I commented in the PR, but should done it here instead.  What's wrong with moving `-documentation` builds to Bionic?  We should do that anyway as part of the Bionic transition.

**Comment by EricCousineau-TRI** [comment]
> I commented in the PR, but should done it here instead. What's wrong with moving -documentation builds to Bionic? We should do that anyway as part of the Bionic transition.

I have nothing wrong with that in terms of getting an archive to be deployed.

However, as indicated by the filing of #9657, it'd be nice if there were as few mysterious differences between locally generated doc and the deployed documentation.
As it stands, users may encounter random differences, and I'd prefer if there were fewer questions to answer. (Also, I'd like there to be quicker feedback, rather than merging a PR, waiting for the upload, etc., to validate Python docstring changes.)

**Comment by jamiesnape** [comment]
I think in this case, the simplicity of using system packages outweighs a few questions. I honestly don't think that many people will generate documentation locally and we do have the same issue with Doxygen (may even more so) and we not going to vendor that in too.

**Comment by jwnimmer-tri** [comment]
To mitigate the hazard of a user previewing pydrake docs on Xenial and being confused, it would be fine to update our `documentation_instructions.rst` to say that users should run them on Bionic in order to see what the real website will be using.  Drake devs will all be on Bionic in a month or two, so the pain of lying previews on Xenial will be short-lived.

**Comment by EricCousineau-TRI** [comment]
That sounds good, as long as we put an inline disclaimer about Bionic support being experimental (per our "Support Configurations" page), or we wait to advertise this until it's fully supported and part of experimental CI.

**Comment by RussTedrake** [comment]
can I ask that we add support for @system{@input_port{name}, } etc from doxygen to the list?  Currently the doxygen macros are just being pushed through verbatim.
https://drake.mit.edu/pydrake/pydrake.systems.primitives.html#pydrake.systems.primitives.Adder_

**Comment by EricCousineau-TRI** [comment]
Yup! If you're OK with it staying in this overall list, I've added it in here.

**Comment by RussTedrake** [comment]
ping.   Resolving Item 19 on this list would probably go a long way to help students use the system workflow via pydrake.  (as discussed on slack after the feedback from the fall class).

**Comment by EricCousineau-TRI** [comment]
For Item (9) - @henryii (on a separate channel) pointed out some filtering that MyPy does for interpreting pybind11 stubs:
https://github.com/python/mypy/pull/9903
Ideally, this could be applied to Sphinx to make things a bit better.

(I'm currently browsing through stuff like `RenderCameraCore` etc., and haven't a whole bunch of cruft text doesn't help :sweat_smile:)

**Comment by EricCousineau-TRI** [comment]
Also for Item (9) - from @sizmailov on [pybind11 gitter](https://gitter.im/pybind/Lobby?at=605dcbca3b9278255bd54a10):
> FYI: If you are open to consider an alternative to sphinx, the [mcss](https://mcss.mosra.cz) project looks like a viable candidate with [built-in pybind11 support](https://mcss.mosra.cz/documentation/python/#pybind11-compatibility).

**Comment by jwnimmer-tri** [comment]
> (6.) All sphinx warnings should be repaired, and then the rule should use -W -q (to promote them to errors) instead of -Q (silencing all warnings).

In my experience, trying to resolve _all_ warnings from API documentation processors is an impractical task.  Sometimes, the complaints just don't matter enough to be worth circling back to fix.

I'll suggest that a more plausible approach would be to use allow- and deny- lists for warning categories.  Certain warnings may be important enough that they should always be promoted to errors.  Certain warnings may be uninportant enough that they should be silenced by default.  This is similar to what we do with compilers, where there are classes of warnings and we tune `-Werror=foo` and `-Wno-to` to provide the best true/false positive experience.

In #15455, I've started doing this on the doxygen_cxx side, by post-processing the console output of Doxygen.

If Sphinx has calibration flags to turn on/off its specific warnings, that would be ideal, but even without that, processing the console output can go a long way.

**Comment by jwnimmer-tri** [comment]
Per my above, my vote is to skip (6).  I think maybe (9) is already solved (upstream?).

That only leaves (18) remaining.  I guess we should circle back to see if it still a bug.
